allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  2b9d865e-8d61-4c01-b1d6-32e9b42afab8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0b4315ef-5e2b-46e5-86ac-f0e8bdc60e99 # Person
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 78967d0c-febc-4115-a906-f0e35b36b1c0
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ffd40798-cf03-4a0f-bc5c-1015be8c87c9 # Body
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 524628aa-8a52-47fb-a2b1-bd3d22a06602
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: fcd726c3-c8f7-4bef-9dc0-acd0bcffda4b # Kind
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1dba430-8ff1-4f79-a537-81cfe951cb2a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 55631285-6210-4b74-958f-cc70eb7c2069 # Title, as printed
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7686ca9-73ed-486d-98ab-115118225283
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 49455df4-6231-4757-b391-1c7205bfd2d6 # How it ended
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 82aec5ba-27e4-492a-b387-fc939bbfa846
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 73609c97-6d23-4a59-8803-427477b033d3 # Term start, as printed
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad55b7d1-b4e5-47a3-a7bd-a6f6f3700462
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8bfe2011-3f4e-4e37-b09b-79c6eacdeded # Term start, EDTF
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f728a70a-4cbd-4b3c-ae96-073ab25f783f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c9bbf159-b011-4ee0-945e-235e9cdfa0db # Term end, as printed
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c96a1127-ba36-4d8d-8bcf-8e8c5f7c2f2a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f2f2db3e-6445-4c60-aa7a-a2a30314edc7 # Term end, EDTF
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3869646-63fa-4b8e-b734-2578a3cbf324
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f568f5dd-4105-4a0b-89e2-b781df066b51 # Evidence for the start
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 26bb1fb1-f067-4aeb-bb58-a63a9ad54167
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 04e25d74-b910-4996-8e82-17876669f0db # Evidence for the end
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57e88d76-310a-4052-b215-480ba355e154
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 939732e2-23f3-4f3a-acf5-d3ec30ff7bea # Footnotes
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c1f03b3-35f3-4297-be8e-0fb94ac5c8c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 42cc5706-8791-4935-b463-28f759b078cf # Notes Are On
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 61762b44-2b0e-4c39-9937-c729fd3330f2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6327ebb7-725a-49b6-89a2-92f1ba79fe25 # Editor's Notes
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 34a65fd5-308f-4537-9cba-b88511c462c5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6dbb0ffe-ecb5-494d-a363-94afc2a918af # Record Provenance
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65e0af49-4c6d-4308-b322-42293051beb3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c863b608-9f47-45c9-8606-39a27567d86d # Dates in this record
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b137cb42-9a24-4d86-8156-9f48c001b723
            userCondition: null
            warning: null
            width: 100
        name: 'The affiliation'
        uid: 189e7ef2-1475-4a39-ad3a-b060876d0971
        userCondition: null
    thumbFieldKey: null
handle: affiliation
hasTitleField: false
icon: null
name: Affiliation
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: "{affiliationPerson.one().title ?? 'Unknown person'}, {affiliationTitle ?: 'affiliated'}, {affiliationBody.one().title ?? 'unknown body'}"
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
