allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  1be8c85e-eb59-480d-9a77-7fda35ed94b9:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 93b4fcdd-4f7a-4156-8b66-6d05ea6299b1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a115cc39-c178-4730-b5f2-f28e464f67b2 # Submission: status
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3e97a0b3-623f-43e6-b910-8436d0795366
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 98b7cd4c-3685-4e8f-a615-17120ae440b0 # Submission: for record
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 79c8be6e-eeeb-46b4-9926-ac6c0fce4efb
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 70aa428e-6ff4-4fd4-bf31-8d77d0a910be # Submission: kind
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b96cb591-4d6b-48f5-a4a7-c59b4720ae00
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 0d194304-c366-4a14-813b-c43294e9d773 # Submission: who is in it
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9c8baf26-a86a-48a5-a89c-20f769051a68
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e47fea5a-4d0f-48a4-9b17-7456c986a6b4 # Submission: the correction
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fc27246-86e7-4375-80d7-98a3aea5ab92
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4d93dfea-27b5-4d5d-8dfb-16fd2b5bbb7e # Submission: page it is about
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 95a5e34d-2fc7-4b2c-bdb9-c296913083e3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6643f0a1-5f08-42ce-8856-e4d737f1a28b # Submission: when taken
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 68b4ce22-6342-4a44-aeea-7af3ed542f17
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bfa67461-4bf6-4219-b417-1fe7df5285a2 # Submission: taken by
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 196b585a-4ab8-46d8-9870-3d7629bd0fa7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: ea4fd288-245b-40a1-bb78-d01bdf9a6606 # Submission: original held by
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0d465d13-45ed-4e1f-bb94-e5a7d5aa2853
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c5f671aa-ca78-4fab-b100-a7f3dff05aad # Submission: sender
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 57dcf4f9-be0a-452e-8663-d4118967885d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 6806b471-1fcc-4c30-b487-87310ef53637 # Submission: credit asked for
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 74f0b9bc-70a0-4b0c-a41c-83fa9e6537f7
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4bc957b6-dcfd-435d-8dda-dd40f8d80146 # Submission: sender email (private)
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: adb6a3e8-1e33-4858-a73f-59e8f50e8b22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 39ee8334-e985-4f7c-8bca-b3ca21123a50 # Submission: permission given
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 253f9c51-1890-4c40-9d33-0bd796b67dbe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: c053fdc8-0ddf-440f-9692-0d68c5300065 # Submission: files
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2991f446-76f2-4723-93e7-67550d8c2fbf
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: f531d318-e0bf-4792-a2bb-4e8b06671027 # Submission: decision
            handle: null
            instructions: null
            label: null
            oldFieldUid: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1424b119-9452-4333-a5f7-1bb8b0851d1f
            userCondition: null
            warning: null
            width: 100
        name: Submission
        uid: 1005e6dd-a253-4d5c-9ae3-22deb730e49c
        userCondition: null
    thumbFieldKey: null
handle: submission
hasTitleField: true
icon: null
name: Submission
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
