allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  f3ac7c1a-3673-4d0e-90bf-7e7ad8730768:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b1bfac3b-af23-4b6c-b740-6557e071a477
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 46e0adbb-5c7a-4b0c-876f-d1f5bfdca53c # Featured Image
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd981701-d297-4b7f-944a-ea63aaf98319
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 1f1e0b5a-e874-40b9-9a54-cf6acef1dd94 # Body
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4096e7c4-aa9e-4e2e-8c60-2e938a6dbaab
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 345bc614-72e5-4974-baed-bef72b54a866 # Death Date
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69c9d811-c9b4-433f-b618-47fee99a693f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b9d1def6-30f2-4133-8bb0-2b222faad34e # Burial Place
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 35a07a1c-1c2e-4e2e-bb03-ceaefe4c703c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d342f0a0-4ef1-4bb8-830f-fb7b3bfb105c
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 71712435-b6d1-4157-93d5-5a09243930c1 # WM Branch
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1d91a8f-d150-4ee6-b8a3-748f97b8d778
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 69be156f-b53d-43d4-867f-4a81dd907415 # WM Rank
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f314410d-c008-4bf3-bfc2-a4cf59dc2d0e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: d78c1773-e157-47b4-9e4b-a7644b394685 # WM Unit
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c65ecd82-6e11-46b9-8759-ece0ffee47cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: e6d8d39f-eebe-4c3e-90a7-10d20899c999 # WM Conflict
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 49ce6314-e415-40b1-ae1f-72ecf0a2f780
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 9210d98c-d829-46ea-aa5e-7fa6f9d6928c # WM Home of Record
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae9fa961-a2a8-4a27-82d6-b72ef1d5c011
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b1b0dca3-29f6-44e6-99c9-c8893e8abbfa # WM Related Person
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 119d9aa2-fc84-4aae-86e9-4f2e80802e05
            userCondition: null
            warning: null
            width: 100
        name: Service
        uid: 2e0faab6-ae9f-4673-a8b1-950845ddaafa
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a8ef966a-768e-4643-9830-6aa0d566a047 # Legacy Key
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 514d2eff-7dc7-47df-b6f0-dd590b5981d3
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 75145733-21e2-48ad-8719-877284efdc47 # Legacy URL
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8f6af124-dad5-4b74-b679-d7a09351ace5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: a4c70e3a-ff4d-47e1-9242-7cdeeda0ef87 # Source Path
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8d9ca298-c268-4039-9b24-794fb593f59f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: null
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 4b9ddc11-19f2-4c19-b079-bedd7af8656d # Legacy HTML
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2c890d4b-0d86-4e91-b470-645023b47d3d
            userCondition: null
            warning: null
            width: 100
        name: Ingest
        uid: b397a9bc-a8af-4c5a-969d-2499b5388fdf
        userCondition: null
    thumbFieldKey: null
handle: warMemorial
hasTitleField: true
icon: null
name: 'War Memorial'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
