columnSuffix: null
handle: communityAliases
instructions: 'Other or historic names, comma separated.'
name: 'Also Known As'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
