defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 02b2c907-bcc2-485b-b2e8-ce5990c28d48 # Role
handle: roles
maxAuthors: 1
minAuthors: 1
name: Roles
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  3ae144ef-e15a-4685-8fec-8ac0dfa20b68: # SCV History
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
