/**
 * War memorial completeness (Nathan, 1 October 2026: "Audit every war memorial
 * record for completeness and tell me what is missing on each"). Read-only:
 * writes inventory/review/war-memorial-audit.md and prints the summary.
 *
 * The fields a memorial record is expected to carry, in the order a reader looks
 * for them. A field counts as present when it has text (or, for relations and
 * images, at least one item).
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/audit_war_memorials.php'))"
 */

use craft\elements\Entry;

$WANT = ['featuredImage' => 'lead image', 'wmConflict' => 'conflict', 'wmBranch' => 'branch', 'wmRank' => 'rank', 'wmUnit' => 'unit',
    'wmDateOfBirth' => 'date of birth', 'wmBirthplace' => 'birthplace', 'wmHomeOfRecord' => 'home of record', 'wmHighSchool' => 'high school',
    'deathDate' => 'date of death', 'wmIncidentLocation' => 'place of death', 'wmCasualtyType' => 'casualty type', 'wmAgeAtLoss' => 'age',
    'burialPlace' => 'burial', 'wmAwards' => 'awards', 'body' => 'narrative', 'footnotes' => 'sources'];
$rows = []; $missCount = array_fill_keys(array_values($WANT), 0); $all = Entry::find()->section('warMemorials')->status(null)->orderBy('title')->all();
foreach ($all as $e) {
    $h = array_map(fn($f) => $f->handle, $e->getFieldLayout()->getCustomFields()); $miss = [];
    foreach ($WANT as $k => $label) {
        if (!in_array($k, $h, true)) { $miss[] = $label; continue; }
        $v = $e->getFieldValue($k);
        if ($k === 'body') { $has = trim(strip_tags((string)$v)) !== '' || trim((string)$e->wmNarrative) !== ''; }
        elseif ($k === 'footnotes') { $has = (bool)array_filter($v ?? [], fn($r) => is_array($r) && trim((string)($r['note'] ?? '')) !== ''); }
        elseif (is_object($v) && method_exists($v, 'exists')) { $has = $v->exists(); }
        else { $has = trim((string)$v) !== ''; }
        if (!$has) { $miss[] = $label; $missCount[$label]++; }
    }
    $rows[] = [$e, $miss];
}
usort($rows, fn($a, $b) => count($b[1]) <=> count($a[1]) ?: strcmp($a[0]->title, $b[0]->title));
$md = ["# War memorial completeness, " . date('j F Y'), '', count($all) . ' records, ' . count($WANT) . ' expected fields each. Most incomplete first. Generated by scripts/import/audit_war_memorials.php (read-only).', '', '## Fields missing across the memorial', '', '| Field | Records missing it |', '|---|---|'];
arsort($missCount); foreach ($missCount as $l => $n) { $md[] = "| $l | $n |"; }
$md = array_merge($md, ['', '## Each record', '', '| Record | Conflict | Missing |', '|---|---|---|']);
foreach ($rows as [$e, $miss]) { $md[] = "| [{$e->title}]({$e->url}) | " . (trim((string)$e->wmConflict) ?: '?') . ' | ' . (count($miss) ? count($miss) . ': ' . implode(', ', $miss) : 'complete') . ' |'; }
file_put_contents(\Craft::getAlias('@root') . '/inventory/review/war-memorial-audit.md', implode(PHP_EOL, $md) . PHP_EOL);
echo 'wrote inventory/review/war-memorial-audit.md' . PHP_EOL;
foreach ($missCount as $l => $n) { echo str_pad($l, 18) . $n . PHP_EOL; }
echo 'complete records: ' . count(array_filter($rows, fn($r) => !$r[1])) . ' of ' . count($all) . PHP_EOL;
