/**
 * READ ONLY. Editor notes and footnotes are public (Nathan, 3 October 2026:
 * "Review the wording of every note in the archive for a reader who knows
 * nothing about this project. 'Came with the WordPress import' means nothing to
 * them and names an internal process ... references to the import, to
 * WordPress, to migration, to scripts, to our own process").
 *
 * Lists every editorNotes and footnotes row, on every entry, whose wording
 * names the project's own machinery. Notes Leon Worden wrote (legacy-leon
 * sources, and the webmaster notes) are listed apart: they are his words and
 * are not rewritten.
 * Writes inventory/review/note-wording-2026-10-03.md and .json.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/audit_note_wording.php'))"
 */

use craft\elements\Entry;

ini_set('memory_limit', '2048M');
$PAT = '~\b(WordPress|imports?|imported|importer|migrat\w*|scripts?|dry run|applied|apply|batch|database|datab|field|fields|records? #|record id|mirror|SHA-256|sha256|manifest|inventory/|\.php|\.py|\.json|review queue|review screen|queue|Grok|Claude|agent|pipeline|CMS|Craft|control panel|staging|placeholder|backfill\w*|schema|template|EDTF|legacyKey|legacyUrl|slug|entry #|ingest\w*|scrap\w*|OCR|fetched|next to try|to try next|still to (?:try|read|check)|not yet read|read so far|re-encoded|SHA-1|checksums?|repository|commit [0-9a-f]{6,}|this run|reviewer|TODO|in a later pass|the script)\b~i';
$rows = []; $n = 0;
foreach (Entry::find()->status(null)->each(200) as $e) {
    $h = []; foreach ($e->getFieldLayout()->getCustomFields() as $f) { $h[$f->handle] = true; }
    foreach (['editorNotes' => 'note', 'footnotes' => 'note'] as $fld => $col) {
        if (!isset($h[$fld])) { continue; }
        foreach ($e->getFieldValue($fld) ?? [] as $i => $r) {
            if (!is_array($r)) { continue; }
            $t = trim((string)($r[$col] ?? '')); if ($t === '') { continue; }
            $n++;
            $src = (string)($r['source'] ?? ''); $head = (string)($r['heading'] ?? '');
            if (!preg_match_all($PAT, $head . ' ' . $t, $m)) { continue; }
            $rows[] = ['id' => $e->id, 'section' => $e->section->handle, 'title' => $e->title, 'field' => $fld, 'row' => $i, 'source' => $src, 'heading' => $head, 'note' => $t, 'terms' => array_values(array_unique(array_map('strtolower', $m[0]))), 'url' => $e->url];
        }
    }
}
$leon = array_filter($rows, fn($r) => str_starts_with($r['source'], 'legacy'));
$ours = array_filter($rows, fn($r) => !str_starts_with($r['source'], 'legacy'));
$terms = []; foreach ($ours as $r) { foreach ($r['terms'] as $t) { $terms[$t] = ($terms[$t] ?? 0) + 1; } } arsort($terms);
$md = ['# Note wording for a public reader, 3 October 2026', '', "Generated by scripts/import/audit_note_wording.php (read only). $n note and footnote rows in the archive; " . count($ours) . ' of ours name the project\'s own machinery; ' . count($leon) . ' of Leon Worden\'s match a term and are listed apart (not rewritten).', '', '## Terms, in our notes', ''];
foreach ($terms as $t => $c) { $md[] = "- $t: $c"; }
$md[] = ''; $md[] = '## Our notes'; $md[] = '';
foreach ($ours as $r) { $md[] = "- {$r['section']} #{$r['id']} {$r['title']} ({$r['field']} {$r['row']}" . ($r['heading'] ? ", \"{$r['heading']}\"" : '') . '): ' . $r['note']; }
$md[] = ''; $md[] = '## Leon Worden\'s, for reference'; $md[] = '';
foreach ($leon as $r) { $md[] = "- {$r['section']} #{$r['id']} {$r['title']}: " . mb_substr($r['note'], 0, 200); }
file_put_contents(\Craft::getAlias('@root') . '/inventory/review/note-wording-2026-10-03.md', implode(PHP_EOL, $md) . PHP_EOL);
file_put_contents(\Craft::getAlias('@root') . '/inventory/review/note-wording-2026-10-03.json', json_encode(array_values($rows), JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES));
echo "$n rows; ours " . count($ours) . "; Leon's " . count($leon) . PHP_EOL . json_encode($terms) . PHP_EOL;
