/**
 * The City of Santa Clarita #394, built out the way California Star Oil Works
 * was: a sourced body, footnotes, the communities it covers, and a map.
 *
 * Nathan, 29 September 2026. The body it replaces is the unsourced paragraph
 * from the WordPress import ("a suburban city in northwestern Los Angeles
 * County ..."); it stays in the record's revision history. The featured image
 * waits for a real photograph (the one supplied was generated by Adobe
 * Firefly and deleted).
 *
 * What the sources settled, against what is usually said:
 *   - The first council was McKeon, Heidt, Darcy, Boyer and Koontz. Vacar,
 *     sometimes listed, was sixth.
 *   - The area at incorporation was 39.79 square miles in the City's own table
 *     of annexations; 39.5, the usual figure (and Leon's, on record #4255),
 *     has no official source found.
 *   - Newhall, Saugus, Valencia and Canyon Country are not wholly inside the
 *     city: the County also lists unincorporated areas under the same names.
 *   - Castaic is not in the city, whatever some encyclopedias say.
 * The German Wikipedia article was read as a finding aid only.
 *
 * THE MAP. The organization page now draws the city's boundary from
 * web/data/communities.geojson (feature santa-clarita), with City Hall as the
 * pin; that is a template change and needs no write here.
 *
 * THE COMMUNITIES. neighborhood already names Newhall, Saugus, Valencia and
 * Canyon Country; Fair Oaks Ranch (annexed 2012) and Sand Canyon (annexed in
 * part, 2012 to 2018) are added. Placerita Canyon is not: no source read puts
 * any of it in the city.
 *
 * Replaces the body and footnotes, which Nathan asked for; every other field
 * fills only when empty. Idempotent. Dry run by default.
 * Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/build_city_of_santa_clarita.php'))"
 */

use craft\elements\Entry;
use craft\elements\Category;

$APPLY = false;
if ($APPLY) { echo 'APPLY IS ON, this will write to the database' . PHP_EOL; }
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL . str_repeat('=', 78) . PHP_EOL;

$CITY = 394;
$OLD_BODY_START = 'Santa Clarita is a suburban city in northwestern Los Angeles County';
$fn = fn(array $notes): array => array_map(fn($i, $n) => ['number' => (string)($i + 1), 'note' => $n, 'source' => 'editorial-2026'], array_keys($notes), $notes);

$CLERK = 'City of Santa Clarita, City Clerk, General Municipal Elections: Historical Election Results, https://santaclarita.gov/city-clerk/wp-content/uploads/sites/8/2023/06/historical-results-7.pdf';
$PROFILE = 'City of Santa Clarita, Community Profile, https://santaclarita.gov/wp-content/uploads/sites/42/migration/Community_Profile.pdf';
$ANNEX = 'City of Santa Clarita, GIS, table of annexations, "Last updated: November 2022," https://santaclarita.gov/wp-content/uploads/sites/42/migration/annex_updated.pdf';
$COUNCIL = 'City of Santa Clarita, City Council, https://santaclarita.gov/city-council/';
$DISTRICTS = 'City of Santa Clarita, District Elections, https://santaclarita.gov/district-elections/';
$ORD = 'City of Santa Clarita, Ordinance No. 23-4, adopted 13 June 2023, https://santaclarita.gov/wp-content/uploads/2023/11/2023-06-13-ORDINANCES-BY-DISTRICT-ELECTIONS.pdf';
$COUNTY_SD5 = 'County of Los Angeles, Fifth Supervisorial District, Guide to Unincorporated Area Services, 2024, https://lacounty.gov/wp-content/uploads/2024/05/SD5-English-Guide-to-Unincorporated-Area-Services-1-1.pdf';
$DEMOG = 'City of Santa Clarita, Demographics, https://santaclarita.gov/community-development/demographics/, read 29 September 2026';
$GAZ = 'U.S. Census Bureau, 2020 Gazetteer, places, California, https://www2.census.gov/geo/docs/maps-data/data/gazetteer/2020_Gazetteer/2020_gaz_place_06.txt';

$BODY = implode("\n\n", [
    'The City of Santa Clarita was incorporated on 15 December 1987, from the communities of Newhall, Saugus, Valencia and Canyon Country.[1] It is a general-law city with a council-manager government: five council members, elected to staggered four-year terms, who each December choose one of themselves to serve a year as mayor.[1][2]',
    'On 3 November 1987 the voters of the proposed city approved incorporation, Proposition U, by 14,723 votes to 6,597, and in Proposition V chose to elect the council at large rather than by district, by 11,166 to 7,905. From 26 candidates they elected Howard P. "Buck" McKeon, with 9,855 votes, Janice Heidt, 8,402, Jo Anne Darcy, 7,601, Carl Boyer III, 6,585, and Dennis M. Koontz, 6,164. Richard M. Vacar, sometimes listed among the first council, was sixth, with 5,935. The ballots cast numbered 21,918.[3]',
    'The council was elected at large for thirty-five years. A suit under the California Voting Rights Act, filed on 29 December 2021, was settled on 12 April 2022,[4] and Ordinance No. 23-4, adopted on 13 June 2023 by four votes to one, divided the city into five council districts. Districts 1 and 3 elected their members in 2024; Districts 2, 4 and 5 elect theirs in 2026.[5]',
    'At incorporation the city covered 39.79 square miles; the figure usually given, 39.5, has not been found in an official source. Forty-one annexations since, among them Fair Oaks Ranch and West Sand Canyon in 2012 and Tesoro del Valle in 2022, have brought it to 73.66 square miles.[6] The City estimated its population at 230,428 on 1 January 2025.[7]',
    'Newhall, Saugus, Valencia and Canyon Country lie mostly inside the city, but the County also lists unincorporated areas under the same names; Fair Oaks Ranch was annexed in 2012, Tesoro del Valle in 2022, and Sand Canyon in parts between 2012 and 2018.[6][8] Stevenson Ranch, Castaic, Val Verde, Agua Dulce, Acton, Bouquet Canyon and San Francisquito Canyon are unincorporated, governed by the County of Los Angeles.[8] Castaic has never been part of the city.',
]);
$FOOTNOTES = $fn([
    $PROFILE . ': "On December 15, 1987, the City of Santa Clarita was incorporated"; "General-law City operating under a Council-Manager form." ' . $ANNEX . ': Santa Clarita, 1987-12-15.',
    $COUNCIL . ': the council "designates one of its members to serve as Mayor," each year at its first meeting in December. ' . $DISTRICTS . ': five members, four-year staggered terms.',
    $CLERK . ', November 3, 1987: Proposition U, Incorporation of City of Santa Clarita, Yes 14,723, No 6,597; Proposition V, Council Elected by District or at Large, By District 7,905, At Large 11,166 (printed "11.166"); 21,918 votes cast; 26 candidates.',
    'PublicCEO, on the settlement approved by the council on 12 April 2022: "Council approved a settlement agreement on April 12"; the suit was brought by Michael Cruz, Sebastian Cazares and Neighborhood Elections Now. ' . $DISTRICTS . ' names the case as "Cruze et al."',
    $ORD . ': "PASSED, APPROVED, AND ADOPTED this 13th day of June 2023," adding Santa Clarita Municipal Code section 2.04.005. ' . $DISTRICTS . ': "In 2024 ... District 1 and District 3."',
    $ANNEX . ': Santa Clarita at incorporation 39.79 square miles (25,463 acres); 41 annexations totalling 33.88 square miles; the city now 73.66 square miles (47,137 acres). Fair Oaks Ranch / West Sand Canyon, 11 September 2012, 3.81 square miles; South Sand Canyon, 16 April 2013; North Sand Canyon, 15 November 2018; Tesoro del Valle, 14 November 2022, 2.79 square miles. The City\'s city-profile page says "39 square miles." ' . $GAZ . ' gives 70.753 square miles of land in 2020, before the Tesoro annexation.',
    $DEMOG . ': 230,428 as of 1 January 2025. The 2020 census count, 228,673, is reported by the Census Bureau\'s QuickFacts, which could not be read directly.',
    $COUNTY_SD5 . ': lists as unincorporated areas Stevenson Ranch, Castaic, Val Verde, Agua Dulce, Acton, Bouquet Canyon and San Francisquito Canyon, and also areas under the names Newhall, Saugus, Valencia, Canyon Country, Sand Canyon and Placerita Canyon.',
]);

$elements = Craft::$app->getElements();
$c = Entry::find()->id($CITY)->status(null)->one();
if (!$c || $c->title !== 'The City of Santa Clarita') { echo "REFUSING: #$CITY is not The City of Santa Clarita" . PHP_EOL; return; }
$body = trim((string)$c->body);
$set = [];
if ($body === trim($BODY)) { echo 'body: already built' . PHP_EOL; }
elseif ($body === '' || str_starts_with($body, $OLD_BODY_START)) { $set['body'] = $BODY; echo 'body: replaces the WordPress paragraph (' . mb_strlen($body) . ' chars, kept in the revision history)' . PHP_EOL; foreach (explode("\n\n", $BODY) as $i => $p) { echo '   P' . ($i + 1) . ': ' . $p . PHP_EOL; } }
else { echo 'REFUSING the body: it is neither empty nor the WordPress paragraph; someone has edited it' . PHP_EOL; }
$curNotes = array_values(array_filter($c->footnotes ?? [], fn($r) => is_array($r) && trim((string)($r['note'] ?? '')) !== ''));
if (!$curNotes || isset($set['body'])) { if ($curNotes && !isset($set['body'])) { echo 'REFUSING the footnotes: already present' . PHP_EOL; } else { $set['footnotes'] = $FOOTNOTES; echo 'footnotes: ' . count($FOOTNOTES) . PHP_EOL; } }
if ($c->getFieldLayout()->getFieldByHandle('recordProvenance') && trim((string)$c->recordProvenance) === '') { $set['recordProvenance'] = 'editorial-2026, build_city_of_santa_clarita.php, 29 September 2026; replaces the unsourced WordPress-import paragraph'; }

$have = array_map('intval', $c->neighborhood->ids());
$add = [];
foreach (['fair-oaks-ranch', 'sand-canyon'] as $slug) { $t = Category::find()->group('neighborhood')->slug($slug)->one(); if (!$t) { echo "community $slug not found" . PHP_EOL; continue; } if (!in_array($t->id, $have, true)) { $add[] = $t; } }
if ($add) { $set['neighborhood'] = array_merge($have, array_map(fn($t) => $t->id, $add)); echo 'communities: keeps ' . implode(', ', array_map(fn($t) => $t->title, $c->neighborhood->all())) . '; adds ' . implode(', ', array_map(fn($t) => $t->title, $add)) . PHP_EOL; }
echo PHP_EOL . 'LEFT: featuredImage (waits for a real photograph); orgWebsite still reads https://www.santa-clarita.com, which the City has moved to santaclarita.gov, kept for Nathan.' . PHP_EOL;
if (!$APPLY) { echo str_repeat('=', 78) . PHP_EOL . 'nothing was written. Set $APPLY = true to apply.' . PHP_EOL; return; }
if (!$set) { echo 'nothing to do; a second run is a no-op' . PHP_EOL; return; }

$c->setFieldValues($set);
if (!$elements->saveElement($c)) { throw new \RuntimeException('build_city: ' . json_encode($c->getFirstErrors())); }
$b = Entry::find()->id($CITY)->status(null)->one();
$short = [];
if (isset($set['body']) && trim((string)$b->body) !== trim($BODY)) { $short[] = 'body differs'; }
if (isset($set['footnotes']) && count(array_filter($b->footnotes, fn($r) => trim((string)($r['note'] ?? '')) !== '')) !== count($FOOTNOTES)) { $short[] = 'footnote count'; }
foreach ($add as $t) { if (!in_array($t->id, array_map('intval', $b->neighborhood->ids()), true)) { $short[] = 'missing community ' . $t->title; } }
echo 'READ-BACK ' . ($short ? 'SHORT: ' . implode('; ', $short) : 'OK') . PHP_EOL;
$applyLog = require \Craft::getAlias('@root') . '/scripts/import/_apply_log.php';
$applyLog('build_city_of_santa_clarita.php', 1, $short ? 'SHORT: ' . implode('; ', $short) : 'verified', 'City of Santa Clarita body, 8 footnotes, communities');
if ($short) { throw new \RuntimeException('build_city_of_santa_clarita: ' . implode('; ', $short)); }
