/**
 * California State University, Northridge #16347: a body scoped to the
 * university's relationship with the Santa Clarita Valley, not its
 * institutional history (Nathan, 29 September 2026).
 *
 * The institutional facts are the three Nathan named, from the university's
 * own history page: San Fernando Valley State College on 1 July 1958, the
 * present name from 1972, the 1994 earthquake's damage. Everything else is
 * what the archive itself holds that passes through CSUN, found by reading
 * every record that names it (15): the Castaic Reservoir archaeology of 1970,
 * a manuscript Reynolds cites, CSUN scholarship on the secession movements,
 * and valley people who studied there. The body says plainly that the archive
 * holds nothing of the university's own, rather than padding it from
 * Wikipedia, which stays an external link.
 *
 * No image: the one supplied was generated by Adobe Firefly and was deleted.
 *
 * Fills empty fields; appends aliases and the event link without removing
 * anything. The existing alias "California State University" names the whole
 * system, not this campus; it is kept and reported. Idempotent. Dry run by
 * default. Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/build_csun_record.php'))"
 */

use craft\elements\Entry;

$APPLY = false;
if ($APPLY) { echo 'APPLY IS ON, this will write to the database' . PHP_EOL; }
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL . str_repeat('=', 78) . PHP_EOL;

$CSUN = 16347; $QUAKE = 875;
$HIST = 'California State University, Northridge, "CSUN History & Leadership," https://www.csun.edu/about/history, read 29 September 2026';
$fn = fn(array $notes): array => array_map(fn($i, $n) => ['number' => (string)($i + 1), 'note' => $n, 'source' => 'editorial-2026'], array_keys($notes), $notes);

$BODY = implode("\n\n", [
    'California State University, Northridge, stands in the San Fernando Valley, over the Newhall Pass from the Santa Clarita Valley. It began as a satellite campus of what is now California State University, Los Angeles, holding its first classes on 24 September 1956; it became San Fernando Valley State College on 1 July 1958, and took its present name in 1972.[1] The Northridge earthquake of 17 January 1994 did more than $400 million of damage to its buildings.[1]',
    'The archive holds nothing of the university\'s own: no photographs of the campus, no documents it issued. What it holds is where the valley\'s story passes through it. Archaeologists from CSUN and UCLA recovered 70 items from Elderberry Canyon, in the Castaic Reservoir area, in 1970, and much of the material from the valley\'s prehistoric sites went into the university\'s collections.[2][3] Jerry Reynolds cites an undated manuscript held at CSUN in his History of the Santa Clarita Valley.[4] Two CSUN political scientists, Tom Hogen-Esch and Martin Saiz, have written on the county-secession movements, of which the Santa Clarita Valley\'s Canyon County campaigns were one.[5]',
    'Among the valley\'s people in the archive who studied there are Richard "Doc" Rioux, with a bachelor\'s degree in history in 1968 and a master\'s in 1971;[6] Marc Winger, superintendent of the Newhall School District from 1997 to 2015, who took his administrative services credential there in 1980;[7] Assemblyman Jim Keysor, who did graduate work at San Fernando Valley State College;[8] Dante Acosta;[9] and teachers and graduates of the valley\'s own schools.[10]',
]);
$FOOTNOTES = $fn([
    $HIST . ': "held its first classes on September 24, 1956"; "on July 1, 1958 to become San Fernando Valley State College (SFVSC)"; renamed three years after James Cleary became president in 1969; the 1994 earthquake left the university with "over $400 million in damages to buildings and infrastructure." The earthquake is record #875.',
    'Jerry Reynolds, "Ethnography of Castaic," record #2175: the Castaic Reservoir collection 2 "consists of 70 items recovered from Elderberry Canyon by archaeologists from UCLA and CSUN in 1970."',
    'Leon Worden, "Ancient SCV Women Did All the Work," The Signal, 14 June 1995, record #12492: the finds went to "a box in the deep, dark recesses of Cal State Northridge."',
    'Jerry Reynolds, History of the Santa Clarita Valley, bibliography, record #2171: an "Undated manuscript, California State University, Northridge."',
    'Record #4921, "Secession Campaign Bumper Sticker, 1976," quoting Tom Hogen-Esch and Martin Saiz of CSUN on California\'s county-secession movements.',
    'Richard "Doc" Rioux, biographical sketch, record #12854: "BA in History, California State University, Northridge (1968)," MA 1971. His own column, record #12798, 12 January 1997.',
    'Record #4015, "Dr. Marc Winger, Superintendent 1997-2015," Newhall School District: "California Administrative Services Credential, California State University, Northridge, 1980."',
    'Record #4181, "1972 Campaign Ephemera," Assemblyman Jim Keysor: "San Fernando Valley State College (graduate work)."',
    'Person record #341, Dante Acosta: "attended California State University, Northridge."',
    'Patti Rasmussen, "Two Rosedell teachers come full-circle," 27 September 1997, record #12680; "Saletore: Young At Hart," The Gazette, February-March 2008, record #12593.',
]);
$ADD_ALIASES = ['San Fernando Valley State College', 'Cal State Northridge', 'CSUN'];

$elements = Craft::$app->getElements();
$o = Entry::find()->id($CSUN)->status(null)->one();
if (!$o || $o->title !== 'California State University, Northridge') { echo "REFUSING: #$CSUN is not CSUN" . PHP_EOL; return; }
$set = [];
foreach (['body' => $BODY, 'footnotes' => $FOOTNOTES, 'dateFounded' => 'July 1, 1958', 'dateFoundedEdtf' => '1958-07-01',
    'orgWebsite' => 'https://www.csun.edu', 'orgWikipediaUrl' => 'https://en.wikipedia.org/wiki/California_State_University,_Northridge',
    'recordProvenance' => 'created from review, 2026-09-21; body editorial-2026, build_csun_record.php, 29 September 2026'] as $h => $v) {
    if (!$o->getFieldLayout()->getFieldByHandle($h)) { echo "   REFUSING $h: not on the layout" . PHP_EOL; continue; }
    $cur = $o->getFieldValue($h);
    $empty = is_array($cur) || $cur === null ? !array_filter((array)$cur, fn($r) => is_array($r) && array_filter($r)) : ($cur instanceof \craft\fields\data\LinkData ? (string)$cur->getUrl() === '' : trim((string)$cur) === '');
    if ($empty || $h === 'recordProvenance') { $set[$h] = $v; echo '   ' . str_pad($h, 18) . (is_array($v) ? count($v) . ' footnotes' : (mb_strlen($v) > 100 ? mb_substr($v, 0, 100) . '... (' . mb_strlen($v) . ' chars)' : $v)) . PHP_EOL; }
    else { echo '   ' . str_pad($h, 18) . '(already set, kept)' . PHP_EOL; }
}
$aliases = array_values(array_filter(array_map('trim', preg_split('~[\n,;]~', (string)$o->orgAliases))));
$add = array_values(array_diff($ADD_ALIASES, $aliases));
if ($add) { $set['orgAliases'] = implode("\n", array_merge($aliases, $add)); echo '   orgAliases        + ' . implode(', ', $add) . ' (keeps "' . implode('", "', $aliases) . '", which names the whole system: for Nathan)' . PHP_EOL; }
$ev = array_map('intval', $o->orgEvents->status(null)->ids());
if (!in_array($QUAKE, $ev, true)) { $set['orgEvents'] = array_merge($ev, [$QUAKE]); echo "   orgEvents         + #$QUAKE Northridge Earthquake" . PHP_EOL; }
echo PHP_EOL . 'NO IMAGE: waits for a real photograph.' . PHP_EOL;
if (!$APPLY) { echo str_repeat('=', 78) . PHP_EOL . 'nothing was written. Set $APPLY = true to apply.' . PHP_EOL; return; }
if (!$set) { echo 'nothing to do; a second run is a no-op' . PHP_EOL; return; }
$o->setFieldValues($set);
if (!$elements->saveElement($o)) { throw new \RuntimeException('build_csun_record: ' . json_encode($o->getFirstErrors())); }
$b = Entry::find()->id($CSUN)->status(null)->one();
$short = [];
if (isset($set['body']) && trim((string)$b->body) !== trim($BODY)) { $short[] = 'body differs'; }
if (isset($set['orgEvents']) && !in_array($QUAKE, array_map('intval', $b->orgEvents->status(null)->ids()), true)) { $short[] = 'earthquake not linked'; }
echo 'READ-BACK ' . ($short ? 'SHORT: ' . implode('; ', $short) : 'OK') . PHP_EOL;
$applyLog = require \Craft::getAlias('@root') . '/scripts/import/_apply_log.php';
$applyLog('build_csun_record.php', 1, $short ? 'SHORT: ' . implode('; ', $short) : 'verified', 'CSUN body scoped to the valley, 10 footnotes');
if ($short) { throw new \RuntimeException('build_csun_record: ' . implode('; ', $short)); }
