/**
 * The 25 blank records, batch 4: the four that waited on the Reggie mirror. The
 * Bennett-Arcan Party, Henry Mayo Newhall Memorial Hospital, the Santa Clarita
 * Valley Chamber of Commerce and Santa Clarita Valley Water.
 *
 * The Bennett-Arcan Party is kept, not retired: the mirror names it on four
 * pages (hs9401, wheat-49ers, earle-mining-0103, and Robinson 1967, page 17, as
 * "Bennett-Arcane"), and Jerry Reynolds tells its story in chapter 19, #859.
 *
 * Written from archive records and from pages read from the Reggie mirror and
 * verified against its manifest (batch9-sha.json). Where sources disagree the
 * body says so: Asahel or Asabel Bennett; the Chamber's first secretary; the
 * year it became the Newhall-Saugus-Valencia Chamber; the year the Castaic Lake
 * Water Agency took over the Santa Clarita Water Company. Every withheld
 * WordPress sentence these replace is left in withheldBody, untouched.
 * Idempotent. Dry run by default. Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/build_blank_records_4.php'))"
 */

use craft\elements\Entry;

$APPLY = false;
if ($APPLY) { echo 'APPLY IS ON, this will write to the database' . PHP_EOL; }
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL . str_repeat('=', 78) . PHP_EOL;
$root = \Craft::getAlias('@root'); $F = "$root/inventory/legacy/fetched"; $els = Craft::$app->getElements();
$ws = fn($s) => trim(preg_replace('~\s+~u', ' ', str_replace(["\u{2019}", "\u{2018}", "\u{201C}", "\u{201D}", "\u{00A0}"], ["'", "'", '"', '"', ' '], html_entity_decode(strip_tags((string)$s), ENT_QUOTES))));
$VERIFIED = [];
foreach (['batch4', 'batch5', 'batch6', 'batch7', 'batch8', 'batch9'] as $b) { $VERIFIED += json_decode((string)@file_get_contents("$F/$b-sha.json"), true)['files'] ?? []; }
$read = function ($src) use ($ws, $F, $VERIFIED) {
    if (is_string($src)) { return isset($VERIFIED["$src.htm"]) && hash_file('sha256', "$F/$src.htm") === $VERIFIED["$src.htm"] ? $ws(@file_get_contents("$F/$src.txt")) : ''; }
    return $ws(Entry::find()->id($src)->status(null)->one()?->body);
};
$fn = fn(array $notes): array => array_map(fn($i, $n) => ['number' => (string)($i + 1), 'note' => $n, 'source' => 'editorial-2026'], array_keys($notes), $notes);
$LEGACY = fn($k, $title) => "$title, as carried on SCVHistory.com, /scvhistory/$k.htm.";

$R = [];
$R[948] = ['title' => 'Bennett-Arcan Party',
    'must' => [859 => ['In March 1849, Asabel Bennett formed a wagon train with the Arcan family and others. Totaling about twenty-five, they headed west from Wisconsin', 'where they learned of a shortcut called the Williams Road. On October 7 the Jayhawker Party of fifteen wagons rumbled up alongside of them', 'Only thirteen adults and seven children survived, huddling under the wrecks of their wagons and eating their emaciated oxen', 'On November 4, two young men from the Bennett-Arcan party', 'William Lewis Manly, twenty-nine, and John Rogers, twenty-two', 'set out for help with a canteen of water and some jerky', 'was like getting a glimpse of Paradise, and tears of joy ran down our faces', 'Vaqueros of Rancho San Francisco brought the pair to the main house on January 1, 1850. There they were fed, clothed and sent back with supplies', 'Doña Jacoba pressed oranges into their hands as they left. "For the little ones," she said', 'young Sara Bennett whispered, "Good-bye, Death Valley." And so it is still known'],
        'hs9401' => ['the Del Valle ranch home (where the 29-year-old Manly and John Rogers, 22, found salvation for the Bennett-Arcan Party on Jan. 1, 1850)', 'Map drawn in pencil by William Lewis Manly, probably in 1894'],
        'earle-mining-0103' => ['They camped at Barrel Springs, several miles to the west of Little Rock Creek, before heading down to the Santa Clarita-Saugus area', 'Manley and Rogers then returned on foot to Death Valley to bring the Bennett-Arcan party out to safety via the same route'],
        'robinson1967p17' => ['Bennett-Arcane party', 'Manly and Rogers left the group'],
        'wheat-49ers' => ['the parties headed respectively by the Reverend James Welsh Brier and by Asahel Bennett'],
        'timeline' => ['February 4: Bennett-Arcan party & Jayhawkers (Death Valley \'49ers) saved when they reach Del Valle ranch headquarters', 'April 22: \'49er patriarch Asahel Bennett of Bennett-Arcan party dies in Idaho Falls']],
    'body' => [
        'The Bennett-Arcan party were gold-seekers stranded in Death Valley in the winter of 1849 and saved by way of the Santa Clarita Valley. Two of their young men, William Lewis Manly and John Rogers, walked out for help, camped at Barrel Springs, came down Soledad Canyon and reached the del Valle family\'s Rancho San Francisco on January 1, 1850. Vaqueros brought them to the main house, where they were fed, clothed and sent back with supplies.[1][2][3][4]',
        'Asahel Bennett had formed the wagon train with the Arcan family and others in March 1849, about twenty-five people bound west from Wisconsin. (Jerry Reynolds spells his name Asabel; Carl Wheat and Leon Worden, Asahel.) In southern Utah they took a shortcut called the Williams Road; the Jayhawker party, which came up alongside them on October 7, would not follow it. The Bennett-Arcan wagons broke down in the desert, and thirteen adults and seven children survived, sheltering under the wrecks and eating their oxen.[1][5][6]',
        'Manly, twenty-nine, and Rogers, twenty-two, had set out on November 4 with a canteen of water and some jerky. Coming down into the valley, Manly later wrote, was "like getting a glimpse of Paradise, and tears of joy ran down our faces." As they left the rancho, Reynolds writes, Doña Jacoba del Valle pressed oranges into their hands "for the little ones."[1] The two walked back and led the party out by the same route.[3] Reynolds tells that as the party crossed the Telescope Mountains young Sara Bennett looked back and whispered "Good-bye, Death Valley," and that the name has stayed.[1] Leon Worden\'s chronology dates the party\'s arrival at the del Valle ranch headquarters, with the Jayhawkers, to February 4, 1850. Manly drew a map of their routes in about 1894, with the del Valle ranch home at the top.[6][2]',
    ],
    'notes' => ['Jerry Reynolds, "Chapter 19. Paradise Found," History of the Santa Clarita Valley, article #859 in this archive, quoting Manly\'s Death Valley in \'49.', $LEGACY('hs9401', '"Death Valley \'49er William Lewis Manly\'s Map, ~1894," HS9401, Santa Clarita Valley Historical Society'), $LEGACY('earle-mining-0103', 'David D. Earle, "Mining and Ranching in Soledad Canyon and Antelope Valley," January 8, 2003'), 'W.W. Robinson, The Story of Valencia and Its Rancho Background (California Land Company, 1967), page 17, as carried on SCVHistory.com, /scvhistory/files/robinson_storyofvalencia_1967/.', $LEGACY('wheat-49ers', 'Carl I. Wheat, "The Forty-Niners in Death Valley: A Tentative Census," Historical Society of Southern California Quarterly, December 1939'), $LEGACY('timeline', 'Leon Worden, "SCV Chronology: A Timeline of Historical Events"')],
];
$R[380] = ['title' => 'Henry Mayo Newhall Memorial Hospital',
    'must' => ['hmnmhstory' => ['when the master planned community of Valencia was approved by Los Angeles County in 1965', 'Newhall Land donated 25 acres of land for a hospital in the center of town', 'the hospital opened for business in August of that year with 100 beds', 'Henry Mayo Newhall Memorial Hospital (popularly called Henry Mayo) is a 227-bed, not-for-profit community hospital and trauma center', 'It continues to be the only hospital in the Santa Clarita Valley'],
        'hmnmhprehistory' => ['when a southbound Greyhound bus slammed into a grain truck that had just pulled onto the fog-shrouded Ridge Route near Castaic', 'Victims were transported to Holy Cross Hospital in Mission Hills and to the little Santa Clarita Hospital', "He occupied one of Santa Clarita Hospital's 19 beds", "which would be called the Santa Clarita Valley Women's Auxiliary", 'After Henry Mayo opened in 1975, hospital volunteers continued to raise funds', "Newhall Land President Thomas L. Lowe recuited Lutheran Hospital Society to organize and finance the valley's first nonprofit, community-owned hospital", 'Newhall Land executives and Newhall family members seeded the endeavor with $1.6 million in cash and stock', 'In 1970 the committee reorganized as the Henry Mayo Newhall Memorial Hospital board and placed Newhall Municipal Court Judge Adrian Adams at the helm', 'Newhall Land pledged a 25-acre site at the future "T" intersection of McBean Parkway and Orchard Village Road', 'in December 1970 the board launched a drive to raise the rest of the $8.5 million needed for construction', 'In February 1971 the board hired its first employee, Bobbie Trueblood', 'now they would have to be reworked to meet evolving seismic safety requirements', 'Project approval came June 25, 1971', 'over objections from Golden State hospital partisans', 'Ground was broken next to the newly extended McBean Parkway in September 1972', "Jane Newhall, great-granddaughter of the hospital's namesake, participates in the September 1972 groundbreaking ceremony", 'LHS took one over when it purchased Inter-Valley to serve as an interim facility. Renamed Hillside Community Hospital', 'Hillside generated about $1 million in profit during this period, which became working capital for the new hospital in Valencia', 'that August with 100 patient beds, a paramedic base station and a 680-square-mile service area', 'The hospital provided the Santa Clarita Valley with its first fully licensed intensive and coronary care units'],
        'aa7402' => ["dedication to the building of Santa Clarita valley's first major hospital"],
        'hm6901' => ['Santa Clarita Hospital will soon be known officially as Inter-Valley Community Hospital', 'Santa Clarita hospital opened its doors in June of 1960']],
    'body' => [
        'Henry Mayo Newhall Memorial Hospital, in Valencia, opened in August 1975 as the Santa Clarita Valley\'s first major hospital, with 100 beds, a paramedic base station and the valley\'s first fully licensed intensive and coronary care units.[1][2][3]',
        'Until then the valley had only small hospitals. On the night of October 12, 1962, a southbound Greyhound bus hit a grain truck on the Ridge Route near Castaic, and the injured were taken to Holy Cross in Mission Hills and to the 19-bed Santa Clarita Hospital in Saugus, opened in 1960. From that night came the Santa Clarita Valley Women\'s Auxiliary, the Pink Ladies and candy stripers, who went on to serve Henry Mayo.[2][4]',
        'When Los Angeles County approved Valencia in 1965, its developer, the Newhall Land and Farming Company, saw that the new town would need a larger hospital. Its president, Thomas L. Lowe, recruited the Lutheran Hospital Society to organize and finance one, and the company pledged a 25-acre site at what would be the meeting of McBean Parkway and Orchard Village Road; Newhall Land executives and members of the Newhall family gave $1.6 million in cash and stock.[1][2] In 1970 the citizens\' committee became the hospital\'s board, under Newhall Municipal Court Judge Adrian Adams, and in December it began a drive to raise the rest of the $8.5 million needed to build. Its first employee, Bobbie Trueblood, was hired in February 1971. That month\'s Sylmar earthquake sent the plans back to be reworked for seismic safety. The county\'s health planning body approved the project on June 25, 1971, over objections from supporters of Golden State hospital, and ground was broken in September 1972, with Jane Newhall, the namesake\'s great-granddaughter, taking part.[2]',
        'While it was built, the Lutheran Hospital Society bought Inter-Valley Community Hospital in Saugus, Santa Clarita Hospital under its 1969 name, and ran it as Hillside Community Hospital, so that doctors and nurses could be recruited before the opening. Hillside\'s profit of about $1 million became the new hospital\'s working capital.[2][4] By the hospital\'s own account in 2012 it had 227 beds and was still the valley\'s only hospital.[1]',
    ],
    'notes' => [$LEGACY('hmnmhstory', 'Henry Mayo Newhall Hospital, "Story of Henry Mayo Newhall Memorial Hospital," 2012'), $LEGACY('hmnmhprehistory', 'Leon Worden, "Volunteers Pave the Way to Henry Mayo Hospital," 2012'), $LEGACY('aa7402', '"Henry Mayo Hospital Board Thanks Ex-Newhall Land President Tom Lowe, 1974," AA7402'), $LEGACY('hm6901', '"Santa Clarita Hospital Changes Name to Inter-Valley, 1969," HM6901')],
];
$R[396] = ['title' => 'Santa Clarita Valley Chamber of Commerce',
    'must' => ['chamber1923-022123' => ['A mass meeting of the residents of Newhall was called to order at 8 o\'clock P.M. in Hap-a-lan Hall', 'Thirty-seven present', 'Moved and carried that the name of the organization be The Newhall Chamber of Commerce', 'A.C. Swall elected unanimously', 'Mr. Perkins withdrew and A.G. Thibaudeau elected unanimously'],
        'scvchamber100_20230223' => ['started life as the Newhall Chamber of Commerce on February 21, 1923', 'Its first president was the local hotelier, Albert Swall, and its first secretary was the grand dame of the community, Armantha Thibeaudau', 'Organize a fire district', 'Remove the annoying street trees that blocked the view of businesses', 'Petition the California Highway Commission to pave the main street, which was a state highway. It finally happened three years later when the county paved it', 'By 1930, the Newhall Chamber had absorbed many of the businesses in the even smaller district of Saugus', 'In 1953, leaders of the Newhall-Saugus Chamber of Commerce were instrumental in bringing one of the "wish list" items of 1923 to fruition: the creation of a public water utility', 'In 1964, they started honoring local business and nonprofit leaders in an annual event that would evolve into the now-independent SCV Man and Woman of the Year celebration', 'would bring unprecedented growth to the area and, in 1967, a name change', 'serving as a de-facto local government for this far-away unincorporated territory, 35 miles distant from the seat of county government', 'when area voters approved an initiative that chamber leaders had been preparing behind the scenes for years: the incorporation of the City of Santa Clarita', 'Starting in 1981, the chamber of commerce, led by then-executive director Jo Anne Darcy', 'The Castaic Chamber, representing the unincorporated area on the northwest, would fold into the Santa Clarita Valley Chamber in 2011, followed by the local Latino Chamber of Commerce in 2015'],
        'scvchamber-presidents' => ['Note: The organization appears to have disbanded after 1923. A 1930 citation refers to it as the Chamber of Commerce of Newhall-Saugus', 'We next hear of it (as the Newhall Chamber) in this 1941 news report', 'Newhall-Saugus-Valencia Chamber of Commerce (Exact year of switch unk.)'],
        'scvnews101517' => ['Newhall County Water District was originally Newhall Water Co. in 1913. It became a public agency in 1953'],
        'pardee-1978chamber' => ['Mr. Pardee moved the house to 24275 Market Street', 'In March 1977, the Newhall-Saugus-Valencia Chamber of Commerce negotiated an indefinite lease'],
        'sg070280' => ['Hereafter the Newhall-Saugus-Valencia Chamber of Commerce shall be titled the Santa Clarita Valley Chamber of Commerce', 'Of the 280 voters, 213 voted yes and 67 voted no', 'Bud Brown, president of the Canyon Country Chamber of Commerce', 'Calling the name change "presumptuous,"', 'finally merged July 1, 1995']],
    'body' => [
        'The Santa Clarita Valley Chamber of Commerce began as the Newhall Chamber of Commerce, organized by thirty-seven residents at a mass meeting in Hap-a-lan Hall on February 21, 1923. They elected the hotelier A.C. Swall president and, by the minutes, A.G. Thibaudeau secretary; Leon Worden\'s centennial history names the first secretary as Armantha Thibeaudau.[1][2]',
        'Its first year\'s aims included a fire district, the removal of street trees that hid businesses from passing motorists, and the paving of the main street, a state highway, which the county paved three years later.[2] By 1930 it had taken in many Saugus businesses, and a 1930 citation calls it the Chamber of Commerce of Newhall-Saugus; the SCVHistory.com list of its presidents notes that it appears to have lapsed after 1923 and names no president again until 1941.[2][3] In 1953 the Newhall-Saugus Chamber\'s leaders were instrumental in creating a public water utility, the Newhall County Water District.[2][4] In 1964 the chamber began honoring local business and nonprofit leaders, the start of the SCV Man and Woman of the Year.[2]',
        'With the founding of Valencia it became the Newhall-Saugus-Valencia Chamber of Commerce, in 1967 by Leon Worden\'s centennial history; the list of presidents gives the year of the change as unknown.[2][3] Speaking for unincorporated territory 35 miles from the county seat, it served, in Worden\'s words, as "a de-facto local government," and its leaders prepared the initiative that incorporated the City of Santa Clarita in 1987.[2] In 1977 it took a lease on the old Pardee House, 24275 Market Street in Newhall, as its headquarters.[5] In 1981, under its executive director Jo Anne Darcy, it began the Walk of Western Stars.[2]',
        'In 1980 its members voted 213 to 67 to rename it the Santa Clarita Valley Chamber of Commerce. Bud Brown, president of the Canyon Country Chamber of Commerce, called the new name presumptuous.[6] The Canyon Country chamber merged into it on July 1, 1995, the Castaic chamber in 2011 and the local Latino Chamber of Commerce in 2015.[6][2]',
    ],
    'notes' => [$LEGACY('chamber1923-022123', '"Newhall Chamber of Commerce: Minutes of 2-21-1923 (First) Meeting"'), $LEGACY('scvchamber100_20230223', 'Leon Worden, "SCV Chamber of Commerce: 100 Years of Service," February 23, 2023'), $LEGACY('scvchamber-presidents', '"Santa Clarita Valley Chamber of Commerce Presidents, 1923 to Date"'), $LEGACY('scvnews101517', 'Leon Worden, "Gov. Brown Signs Wilk Bill Merging SCV Water Agencies," SCVNews.com, October 15, 2017'), $LEGACY('pardee-1978chamber', '"Old Historic Home Becomes New Headquarters for the Newhall-Saugus-Valencia Chamber of Commerce," from the chamber\'s installation program, January 14, 1978'), $LEGACY('sg070280', '"A New Name," The Newhall Signal and Saugus Enterprise, July 2, 1980, with a note on the 1995 merger')],
];
$R[402] = ['title' => 'Santa Clarita Valley Water',
    'must' => ['scvnews101517' => ['With the stroke of his pen Sunday, Gov. Jerry Brown eliminated the Castaic Lake Water Agency and Newhall County Water District and replaced them with a new water agency for the Santa Clarita Valley', 'except in Val Verde, where customers will continue to purchase water from the L.A. County-controlled Water Works District 36', 'since 1999 when it purchased the once-private Santa Clarita Water Co. from Saugus homebuilder Bill Bonelli\'s heirs', 'In 2012 it also bought The Newhall Land and Farming Co.\'s water retailer, Valencia Water Co.', 'Newhall County Water District was originally Newhall Water Co. in 1913. It became a public agency in 1953', 'NCWD was suing CLWA over a hike in the wholesale water rate', 'NCWD challenged the legality of CLWA\'s acquisition of Valencia Water Co.', 'Ultimately the two agencies decided to settle their differences through a merger', 'For electoral purposes, the new agency is divided into three geographic regions. Initially, its 15 members will be the five elected members of the NCWD board and the nine elected members of the CLWA board, plus one appointed seat for District 36'],
        'scvwa010918' => ['On February 17, 2017, California Senator Scott Wilk introduced SB 634, which Governor Brown signed into law on October 15, 2017. The bill established the Santa Clarita Valley Water Agency (SCV Water), effective on January 1, 2018'],
        'scvwa20190618' => ['Santa Clarita Valley Water Agency (SCV Water) was created January 1, 2018 by an act of the State Legislature (SB 634) through the merger of the four water agencies in the Santa Clarita Valley', 'SCV Water provides water services to a population of approximately 273,000 in the Santa Clarita Valley through 72,000 water service connections'],
        'clwa_scwd_2012' => ['The four retail water purveyors are Los Angeles County Waterworks District No. 36, Newhall County Water District (NCWD), Santa Clarita Water Division and Valencia Water Company (VWC)', 'In 1999, the Castaic Lake Water Agency purchased SCWC, and the name was changed to the Santa Clarita Water Division'],
        'clwa102517' => ['when the Castaic Lake Water Agency bought all assets of the private Santa Clarita Water Company for $63 million', 'had been inactive since August 31, 1998, when CLWA absorbed its assets', 'Bonelli\'s Bouquet Canyon Water Company (1949) and Solemint Water Company (1956)'],
        'wa1980' => ['voted April 24, 1962, to connect to the State Water Project, necessitating the formation of the Upper Santa Clara Valley Water Agency', 'The entity was renamed Castaic Lake Water Agency in 1970', 'in 1980, when CLWA began delivering State Water Project water to the Santa Clarita Valley']],
    'body' => [
        'Santa Clarita Valley Water, the Santa Clarita Valley Water Agency, has supplied the valley\'s water since January 1, 2018, when it took the place of four: the Castaic Lake Water Agency, the Newhall County Water District, the agency\'s Santa Clarita Water Division and the Valencia Water Company. Val Verde alone still buys its water from the county\'s Water Works District 36.[1][2][3]',
        'Senator Scott Wilk introduced the bill that created it, SB 634, on February 17, 2017, and Governor Jerry Brown signed it on October 15. The Castaic Lake agency and the Newhall district had been in court with each other, over a rise in the wholesale rate and over the agency\'s purchase of the Valencia Water Company, and settled their differences by merging. The new board was elected from three divisions; at first its fifteen members were the five Newhall and nine Castaic Lake directors and an appointed seat for District 36.[1][3]',
        'The oldest of its forerunners was the Newhall Water Company of 1913, which became a public agency, the Newhall County Water District, in 1953. Valley voters chose on April 24, 1962 to join the State Water Project, which brought the Upper Santa Clara Valley Water Agency into being; it was renamed the Castaic Lake Water Agency in 1970 and began delivering state water to the valley in 1980.[1][5] The agency bought the private Santa Clarita Water Company, built from Bill Bonelli\'s Bouquet Canyon (1949) and Solemint (1956) water companies, for $63 million: in 1999 by the agency\'s 2012 history and Leon Worden\'s 2017 report, while the page on the company\'s 2017 dissolution dates the takeover of its assets to August 31, 1998. It bought Newhall Land\'s Valencia Water Company in 2012.[4][6][1] In 2019 SCV Water served about 273,000 people through 72,000 connections.[2]',
    ],
    'notes' => [$LEGACY('scvnews101517', 'Leon Worden, "Gov. Brown Signs Wilk Bill Merging SCV Water Agencies," SCVNews.com, October 15, 2017'), $LEGACY('scvwa20190618', 'Santa Clarita Valley Water Agency, "5-Year Strategic Plan," adopted June 18, 2019'), $LEGACY('scvwa010918', 'Santa Clarita Valley Water Agency, "Resolution Dissolving Valencia Water Company," for the board meeting of January 9, 2018'), $LEGACY('clwa_scwd_2012', 'Castaic Lake Water Agency, "History & Overview of Santa Clarita Water Co./Division," August 2012'), $LEGACY('wa1980', '"Castaic Lake Water Agency Facility," WA1980'), $LEGACY('clwa102517', '"Santa Clarita Water Company Dissolved," Castaic Lake Water Agency board meeting, October 25, 2017')],
];

$bad = []; $plan = [];
foreach ($R as $id => $c) {
    $e = Entry::find()->id($id)->status(null)->one();
    if (!$e || $e->title !== $c['title']) { $bad[] = "#$id is not {$c['title']}"; continue; }
    foreach ($c['must'] as $src => $ps) { $t = $read($src); foreach ($ps as $ph) { if (!str_contains($t, $ws($ph))) { $bad[] = "{$c['title']}: " . (is_string($src) ? $src : "#$src") . ' does not read "' . mb_substr($ph, 0, 60) . '"'; } } }
    $body = implode("\n\n", $c['body']); $cur = trim((string)$e->body); $done = $cur === $body;
    if ($cur !== '' && !$done) { $bad[] = "{$c['title']}: has a body this does not replace"; }
    preg_match_all('~\[(\d+)\]~', $body, $m); $used = array_unique(array_map('intval', $m[1]));
    if (count($used) !== count($c['notes']) || max($used) > count($c['notes'])) { $bad[] = "{$c['title']}: notes used " . json_encode(array_values($used)) . ' of ' . count($c['notes']); }
    if (preg_match('~\x{2014}~u', $body . implode('', $c['notes']))) { $bad[] = "{$c['title']}: an em dash"; }
    $plan[$id] = [$e, $body, $done];
    echo str_pad($c['title'], 46) . ($done ? 'already written' : str_word_count($body) . ' words, ' . count($c['notes']) . ' notes') . PHP_EOL;
}
echo 'REFUSED: ' . ($bad ? PHP_EOL . '  ' . implode(PHP_EOL . '  ', $bad) : 'none') . PHP_EOL;
if (!$APPLY) { echo str_repeat('=', 78) . PHP_EOL . 'nothing was written. Set $APPLY = true to apply.' . PHP_EOL; return; }
if ($bad) { echo 'REFUSING' . PHP_EOL; return; }
$short = []; $n = 0;
foreach ($plan as $id => [$e, $body, $done]) {
    if (!$done) { $e->setFieldValues(['body' => $body, 'footnotes' => $fn($R[$id]['notes'])]); if (!$els->saveElement($e)) { $short[] = "{$e->title} " . json_encode($e->getFirstErrors()); continue; } }
    $r = Entry::find()->id($id)->status(null)->one(); $ok = trim((string)$r->body) === $body && count($r->footnotes ?? []) === count($R[$id]['notes']);
    $ok ? $n++ : $short[] = $r->title; echo ($ok ? 'OK    ' : 'SHORT ') . $r->title . ' ' . $r->url . PHP_EOL;
}
echo 'READ-BACK ' . ($short ? 'SHORT: ' . implode(', ', $short) : "OK: $n records") . PHP_EOL;
$applyLog = require "$root/scripts/import/_apply_log.php";
$applyLog('build_blank_records_4.php', $n, $short ? 'SHORT' : 'verified', 'the 25, batch 4: Bennett-Arcan Party, Henry Mayo Newhall Memorial Hospital, SCV Chamber of Commerce, SCV Water');
if ($short) { throw new \RuntimeException('build_blank_records_4: ' . implode(', ', $short)); }
