#!/usr/bin/env python3
"""Katie Hill #29332: the profile draft (Nathan, 6 October 2026). Claude Code.

Writes inventory/review/katie-hill-profile-draft-2026-10-06.json (read by
scripts/import/build_hill_profile_2026_10_06.php) and the .md beside it for reading.
The body carries {KEY} markers; they are numbered here by first appearance, one [n] per
note, so a note cited twice keeps its number.

Every quotation below was read in the source named, on 6 October 2026: the mirror pages
from the Reggie mirror (latin-1), the outside sources from the copies saved in
inventory/sources/katie-hill-2026-10-06/ (SHA256SUMS there), the district figures from
templates/_data/valley-districts.json. No quotation joins two clauses with an ellipsis.

She is living: public life only (docs/DATA-MODEL.md). Nathan's brief, 6 October 2026: no
description of the photographs, and no naming of where they appeared, in the text, the
notes or the footnotes. The court is cited by court, docket and date, not by case name.
Run on the host: python3 scripts/import/draft_hill_profile_2026_10_06.py
"""
import json, os, re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
OUT = os.path.join(ROOT, 'inventory', 'review', 'katie-hill-profile-draft-2026-10-06')

NOTES = {
    'SOV': 'California Secretary of State, Statement of Vote, General Election, November 6, 2018, United States Representative, 25th Congressional District, https://elections.cdn.sos.ca.gov/sov/2018-general/sov/48-congress.pdf: "Katie Hill" DEM, "Steve Knight*" REP (the asterisk: "*Incumbent"); Los Angeles 108,355 to 86,562; Ventura 24,854 to 25,251; "District Totals" 133,209 to 111,813; "Percent" 54.4% to 45.6%.',
    'TERM': 'Her term is the archive\'s office holding #29378 (United States House of Representatives, 25th District, 2011 lines, 3 January 2019 to 3 November 2019, ended by resignation). Biographical Directory of the United States Congress, "HILL, Katie," as captured by the Wayback Machine, https://web.archive.org/web/20201125000215id_/https://bioguideretro.congress.gov/Home/MemberDetails?memIndex=H001087: "graduated from Saugus High School, Santa Clarita, Calif., 2004"; "non-profit executive"; "elected as a Democrat to the One Hundred Sixteenth Congress until her resignation on November 3, 2019 (January 3, 2019-November 3, 2019)."',
    'BIO': 'SCVHistory.com, "U.S. Rep. Katie Hill: First 100 Days (Video Highlights), 2019," legacy page /scvhistory/katiehill_100days.htm (not yet a record in the archive). The webmaster\'s introduction: "She lives in Agua Dulce and grew up in Saugus where she attended Highlands Elementary, Arroyo Seco Junior High and Saugus High School". Her official congressional biography, printed below it: "Katie most recently worked as Executive Director of PATH (People Assisting The Homeless), the largest homeless services organization in California"; "She was elected by her colleagues to be the Freshman Co-Representative to Leadership in the 116th Congress".',
    'SEAT': 'The archive\'s office holdings for the valley\'s seat in the House: Buck McKeon #26980 (25th District, 1991 lines, 3 January 1993 to 3 January 2003), #29372 (2001 lines, to 3 January 2013) and #29374 (2011 lines, to 3 January 2015); Steve Knight #29376 (2011 lines, 3 January 2015 to 3 January 2019). The archive\'s count of the valley\'s people by district, templates/_data/valley-districts.json: under the "1991 lines, drawn by the court\'s Special Masters" the 25th held "the whole valley"; under the 2001 lines "All the valley but Green Valley"; under the 2011 lines "The whole valley, with Palmdale, eastern Lancaster and part of Simi Valley". The Signal, Sunday, October 27, 2019, on the archive page /scvhistory/katiehill20191027.htm (not yet a record in the archive): "Hill became the first Democrat to represent the 25th Congressional District in 2018, after it was held by Republicans for more than 26 years." Before the 1991 lines the number belonged to another district: Clerk of the House, Statistics of the Congressional Election of November 6, 1990, page 4, California, "25. Edward R. Roybal, Democrat" 48,120, https://clerk.house.gov/member_info/electionInfo/1990election.pdf. The archive\'s account of the valley\'s districts begins with the 1991 lines, so this note does not say who represented the valley before January 1993.',
    'CMTE': 'Clerk of the House, List of Standing Committees and Select Committees and Their Subcommittees of the House of Representatives, 116th Congress, August 1, 2019, as captured by the Wayback Machine, https://web.archive.org/web/20190807175051id_/http://clerk.house.gov/committee_info/scsoal.pdf: "Hill, Katie, 25th CA", "Armed Services.", "Oversight and Reform.", "Science, Space, and Technology." The Signal, "Hill appointed to House Oversight and Government Reform Committee," published online January 23, 2019 (Pacific time), as captured by the Wayback Machine, https://web.archive.org/web/20191020133736id_/https://signalscv.com/2019/01/hill-appointed-to-house-oversight-and-government-reform-committee/: "the recently elected congresswoman will also have an assignment on the House Committee on Science, Space and Technology, in addition to a previously announced selection to the House Armed Services Committee."',
    'HR1015': 'H.R. 1015, 116th Congress, introduced February 6, 2019, https://www.govinfo.gov/content/pkg/BILLS-116hr1015ih/html/BILLS-116hr1015ih.htm: "Ms. Hill of California (for herself and Ms. Brownley of California) introduced the following bill; which was referred to the Committee on Natural Resources"; "To provide for the establishment of a national memorial and national monument to commemorate those killed by the collapse of the Saint Francis Dam on March 12, 1928, and for other purposes." SCVHistory.com lists it, "Rep. Hill: H.R.1015 (2019)," among its St. Francis Dam pages (legacy page /scvhistory/s47_2019.htm).',
    'S47': 'Clerk of the House, roll call 95, February 26, 2019, S. 47, "Natural Resources Management Act", "On Motion to Suspend the Rules and Pass", passed 363 to 62, https://clerk.house.gov/evs/2019/roll095.xml: "Hill (CA)" "Yea". Public Law 116-9, approved March 12, 2019, https://www.govinfo.gov/content/pkg/PLAW-116publ9/html/PLAW-116publ9.htm: "Sec. 1111. Saint Francis Dam Disaster National Memorial and National Monument"; the section commemorates the victims of "the Saint Francis Dam disaster of March 12, 1928."',
    'ETHICS': 'House Committee on Ethics, "Statement of the Chairman and Ranking Member of the Committee on Ethics Regarding Representative Katie Hill," October 23, 2019, https://ethics.house.gov/press-release/statement-chairman-and-ranking-member-committee-ethics-regarding-representative-katie: "The Committee is aware of public allegations that Representative Katie Hill may have engaged in a sexual relationship with an individual on her congressional staff, in violation of House Rule XXIII, clause 18(a)"; "the mere fact that it is investigating these allegations, and publicly disclosing its review, does not itself indicate that any violation has occurred, or reflect any judgment on behalf of the Committee."',
    'SIG1023': 'Signal Staff, "Ethics Committee investigates allegations of Hill affair with congressional staffer," The Signal, October 23, 2019, as captured by the Wayback Machine, https://web.archive.org/web/20191024143944id_/https://signalscv.com/2019/10/ethics-committee-investigates-allegations-of-hill-affair-with-congressional-staffer/ (the live page is now headed "Congresswoman denies having inappropriate relationship"). From her email to supporters of Wednesday, October 23: "I became involved in a relationship with someone on my campaign"; "I know that even a consensual relationship with a subordinate is inappropriate, but I still allowed it to happen despite my better judgment. For that I apologize." From her statement of Tuesday, October 22: "I have notified Capitol Hill police who are investigating the situation and potential legal violations of those who posted and distributed the photos, and therefore will have no further comment on the digital materials." The Signal: "In an email to supporters Wednesday, Hill denied a relationship with the congressional aide but acknowledged a previous relationship with a campaign staffer."',
    'RULE': 'Rules of the House of Representatives, 116th Congress, Rule XXIII, clause 18(a), House Manual (H. Doc. 115-177), section 1095, https://www.govinfo.gov/content/pkg/HMAN-116/pdf/HMAN-116-houserules.pdf: "A Member, Delegate, or Resident Commissioner may not engage in a sexual relationship with any employee of the House who works under the supervision of the Member, Delegate, or Resident Commissioner, or who is an employee of a committee on which the Member, Delegate, or Resident Commissioner serves."',
    'ANNOUNCE': 'The Signal, Sunday, October 27, 2019, with the text of her announcement, on the archive page /scvhistory/katiehill20191027.htm (not yet a record in the archive): "Hill announced in a tweet Sunday afternoon at 4:03 p.m."; her announcement: "It is with a broken heart that today I announce my resignation from Congress"; "Having private photos of personal moments weaponized against me has been an appalling invasion of my privacy. It\'s also illegal, and we are currently pursuing all of our available legal options."',
    'FLOOR': 'Congressional Record, House, October 31, 2019, H8713, special order "Rise and Make Tomorrow Better Than Today," https://www.congress.gov/116/crec/2019/10/31/CREC-2019-10-31-house.pdf: "Ms. HILL of California. Madam Speaker, this is the last speech that I will give from this floor as a Member of Congress."',
    'LETTER': 'Congressional Record, House, November 5, 2019, H8727, "Resignation from the House of Representatives," https://www.congress.gov/116/crec/2019/11/05/CREC-2019-11-05-pt1-PgH8727.pdf. Her letter to the Speaker, dated November 1, 2019: "I write to inform you that I have notified California Governor Gavin Newsom of my resignation from the U.S. House of Representatives, effective November 3, 2019." Her letter to the Governor, of the same date: "I write to inform you that I will resign my seat in the U.S. House of Representatives, effective November 3, 2019." The Speaker pro tempore, November 5: "in light of the resignation of the gentlewoman from California (Ms. HILL) the whole number of the House is 431."',
    'PROC': 'Governor Gavin Newsom, Special Election Proclamation, November 15, 2019, filed with the Secretary of State the same day, https://elections.cdn.sos.ca.gov/special-elections/2020-cd25/governors-proclamation.pdf: "a special election shall be held on the 12th day of May 2020, within the 25th Congressional District of the State, to fill the vacancy of the office of the Member of Congress from said district resulting from the resignation of Representative Katie Hill." Mike Garcia\'s office holding #29380 (25th District, from May 2020).',
    'STATUTE': 'California Civil Code section 1708.85, subdivision (a), as quoted in the ruling cited in the next note: "A private cause of action lies against a person who intentionally distributes by any means a photograph, film, videotape, recording, or any other reproduction of another, without the other\'s consent". Subdivision (c): "There shall be no liability on the part of the person distributing material under subdivision (a) under any of the following circumstances"; paragraph (4): "The distributed material constitutes a matter of public concern."',
    'RULING': 'Superior Court of California, County of Los Angeles, Department 31 (Judge Yolanda Orozco), No. 20STCV48797, ruling on a defendant\'s special motion to strike, hearing of April 8, 2021 (the filing gives its title as "Distribution of sexually explicit materials; private cause of action; use of pseudonym"): "On December 22, 2020, Plaintiff Katherine Hill filed the instant action"; "Section 1708.85(c)(4) provides for an exception from liability for images which are a matter of public concern"; "Defendant has established that the images are a matter of public concern"; "Defendant\'s special motion to strike is GRANTED." City News Service, December 29, 2023, as carried by KABC-TV (abc7.com): "was the only remaining defendant"; "The media defendants were previously dismissed on free-speech grounds"; "an accord was reached, but no terms were divulged."',
}

BODY = [
    "Katie Hill represented the Santa Clarita Valley in the United States House of Representatives, for the 25th District, from 3 January 2019 until she resigned on 3 November 2019.{TERM} She grew up in Saugus, graduated from Saugus High School in 2004, and in 2019 lived in Agua Dulce.{BIO}{TERM} On 6 November 2018 she won the seat from the incumbent, Steve Knight, by 133,209 votes to 111,813, 54.4 per cent of the vote.{SOV} She was the first Democrat to hold the 25th District since the 1991 lines put the valley in it: Republicans held it from January 1993, Buck McKeon until 2015 and Steve Knight after him.{SEAT}",
    "Before Congress she was the executive director of PATH (People Assisting The Homeless), by her official biography.{BIO} In the House she sat on the Armed Services, Oversight and Reform, and Science, Space, and Technology committees, and by her official biography her colleagues elected her Freshman Co-Representative to Leadership in the 116th Congress.{CMTE}{BIO} On 6 February 2019 she introduced H.R. 1015, with Julia Brownley, to establish a national memorial and national monument to those killed by the collapse of the St. Francis Dam on 12 March 1928.{HR1015} The memorial became law as section 1111 of S. 47, the Natural Resources Management Act, for which she voted when the House passed it on 26 February 2019, by 363 votes to 62; it was approved on 12 March 2019.{S47}",
    "On 23 October 2019 the House Committee on Ethics announced that it was investigating public allegations that she \"may have engaged in a sexual relationship with an individual on her congressional staff,\" in violation of House Rule XXIII, clause 18(a), and stated that the investigation did not itself indicate that any violation had occurred.{ETHICS} She denied the allegation.{SIG1023} The same day, in an email to her supporters, she acknowledged \"a relationship with someone on my campaign\" and apologized for it.{SIG1023} The rule the Committee cited applies to a Member's relationship with an employee of the House who works under the Member's supervision or for one of the Member's committees.{RULE} Intimate photographs of her had been published without her consent; she said that she had notified the Capitol Police, and later that their publication was illegal.{SIG1023}{ANNOUNCE} On 27 October she announced that she would resign.{ANNOUNCE} She gave her last speech on the House floor on 31 October, and on 1 November wrote to the Speaker and to Governor Gavin Newsom that her resignation would take effect on 3 November 2019.{FLOOR}{LETTER} The Governor called a special election for 12 May 2020 to fill the vacancy, and Mike Garcia won it.{PROC}",
    "In December 2020 she sued over the publication of the photographs in the Los Angeles County Superior Court, under California's statute giving a civil claim against distributing sexually explicit material without consent, Civil Code section 1708.85, which excepts material that \"constitutes a matter of public concern.\"{STATUTE} The court struck her claims against the media defendants; in a ruling of April 2021 it found that the images were a matter of public concern under that exception. Her claim against the remaining defendant was settled in December 2023, on terms that were not made public.{RULING}",
]

FIELDS = {
    'bodyAuthorship': 'editorial-2026',
    'occupation': 'Nonprofit executive; congresswoman',
    'wikidataId': 'Q58416634',
    'bioguideId': 'H001087',
    'personWikipediaUrl': 'https://en.wikipedia.org/wiki/Katie_Hill',
    'aliasesAdd': ['Rep. Katie Hill', 'Katherine Hill'],
}

HOLDING_NOTES = {
    29378: 'Congressional Record, House, November 5, 2019, H8727, https://www.congress.gov/116/crec/2019/11/05/CREC-2019-11-05-pt1-PgH8727.pdf: her letter to the Speaker, dated November 1, 2019, "I write to inform you that I have notified California Governor Gavin Newsom of my resignation from the U.S. House of Representatives, effective November 3, 2019." She announced on October 27, 2019 that she would resign (The Signal, October 27, 2019, /scvhistory/katiehill20191027.htm).',
}


FOR_NATHAN = [
    'Correction to the brief, the dates. She announced on 27 October 2019 that she would resign (her announcement, The Signal of that day). 31 October was her last floor speech and her last votes (H. Res. 660, roll calls 603 and 604, Yea). Her letters to the Speaker and to the Governor are dated 1 November and give the effective date as 3 November 2019, and the Biographical Directory agrees ("until her resignation on November 3, 2019"). The archive\'s holding #29378 already ends on 3 November; it stands.',
    'Correction to the brief, "the first Democrat to hold it". The number 25 was held by a Democrat before: Edward R. Roybal, re-elected for the 25th in 1990 (Clerk\'s Statistics, page 4), under the 1981 lines. The draft says what the sources support: the first Democrat to hold the 25th since the 1991 lines put the valley in it (Republicans from January 1993). The Signal\'s own sentence, quoted in note 4: "the first Democrat to represent the 25th Congressional District in 2018, after it was held by Republicans for more than 26 years." Whether she was the first Democrat to represent the valley at all is not established: the archive\'s district data begins in 1993.',
    'Correction to the brief, "unlawful". No court found the publication unlawful. Under Civil Code 1708.85 the Superior Court (No. 20STCV48797) struck her claims against the media defendants, and in its ruling of 8 April 2021 found the images "a matter of public concern" within the statute\'s exception (c)(4); her claim against the remaining defendant settled in December 2023 with no terms disclosed. No criminal charge under Penal Code 647(j)(4) was found reported (web searches, 6 October 2026). So the draft states that they were published without her consent, that she said the publication was illegal (her words, 27 October 2019), and what the court did. Yours: keep the court paragraph, or end at her words. Stating "unlawful" as fact would state more than the source.',
    'Not verified, left out: her testimony for legislation on nonconsensual pornography. Searched 6 October 2026: web searches (standard and extended) for her name with testified, testimony, witness, hearing, SHIELD Act, intimate images, deepfake, California Assembly and Senate committees; the House Oversight hearing "Addressing Real Harm Done by Deepfakes" (CHRG-118hhrg55181, 12 March 2024) witness list (not her). No hearing record or bill found. If you know the bill or hearing, it goes in with the official record.',
    'Her acknowledgment and denial are from her email to supporters of 23 October and her statement of 22 October, as printed by The Signal (note 9). Not quoted, as private life: the passages on her marriage and divorce. The staffer she denied a relationship with is not named in the text or notes.',
    '"Not prohibited by House rules": the draft does not say it in those words. It quotes the rule the Committee cited (Rule XXIII, clause 18(a): a Member and "any employee of the House who works under the supervision of the Member") and lets the reader compare. No source found in which the Committee says so.',
    'The words "Intimate photographs" in the text are from your brief; the notes quote her own phrases ("the photos", "private photos of personal moments"). Nothing describes them. The outlets are not named; where a source names them, that passage is not quoted. The court is cited by court, department, docket and date; the case caption names a private person (it does not name an outlet), so it is not used.',
    'Living: no birth fields set. The Biographical Directory gives her birth date (25 August 1987); yours whether a living member\'s date goes on the record.',
    'Aliases: "Katherine Hill" is the name on her court filing. Drop it if you prefer.',
    'Out of scope, noticed: Mike Garcia\'s holding #29380 starts 12 May 2020, the special election\'s date; a member takes the seat when sworn in, after the election; worth checking against the Clerk\'s record.',
    'Wikipedia (https://en.wikipedia.org/wiki/Katie_Hill) was not used for any fact; it is on the record as a finding aid. The Wikidata item Q58416634 matches by Bioguide id (P1157 H001087).',
]

order, seen = [], {}
def num(m):
    k = m.group(1)
    if k not in seen:
        seen[k] = len(order) + 1; order.append(k)
    return '[%d]' % seen[k]
body = '\n\n'.join(re.sub(r'\{([A-Z0-9]+)\}', num, p) for p in BODY)
unused = [k for k in NOTES if k not in seen]
assert not unused, 'notes never cited: %s' % unused
notes = [{'number': str(i + 1), 'key': k, 'note': NOTES[k]} for i, k in enumerate(order)]

own = body + ''.join(HOLDING_NOTES.values())
assert '—' not in own, 'an em dash in our own text'
for banned in ('RedState', 'Red State', 'Daily Mail', 'Mail Media', 'Salem', 'Van Laar', 'Heslep', 'Messina', 'Kelly', 'nude', 'naked'):
    for n in notes:
        assert banned.lower() not in n['note'].lower(), '%s in note %s' % (banned, n['number'])
    assert banned.lower() not in own.lower(), '%s in the text' % banned

D = {'drafted': '2026-10-06', 'draftedBy': 'scripts/import/draft_hill_profile_2026_10_06.py, Claude Code',
     'person': {'id': 29332, 'title': 'Katie Hill'}, 'body': body, 'footnotes': notes,
     'fields': FIELDS, 'holdingNotes': {str(k): v for k, v in HOLDING_NOTES.items()}}
with open(OUT + '.json', 'w', encoding='utf-8') as f:
    json.dump(D, f, ensure_ascii=False, indent=1)

md = ['# Katie Hill #29332: the profile draft, 6 October 2026', '',
      'For Nathan to read before the loader is applied. Body first, then the notes as they will be numbered. Nothing here is written to Craft; the loader (scripts/import/build_hill_profile_2026_10_06.php) reads the .json beside this file. She is living: public life only. The sources are saved in inventory/sources/katie-hill-2026-10-06/ (SHA256SUMS there).', '',
      '## Body', '', body, '', '## Notes', '']
md += ['%s. %s' % (n['number'], n['note']) for n in notes]
md += ['', '## Other fields', ''] + ['- %s: %s' % (k, v) for k, v in FIELDS.items()]
md += ['', '## Note added to the office holding', ''] + ['- #%s: %s' % (k, v) for k, v in HOLDING_NOTES.items()]
md += ['', '## For Nathan', ''] + ['- ' + x for x in FOR_NATHAN]
with open(OUT + '.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(md) + '\n')
print('wrote %s.json and .md: %d paragraphs, %d notes, %d characters of body' % (OUT, len(BODY), len(notes), len(body)))
