#!/usr/bin/env python3
"""Pete Knight #29314: the profile draft (Nathan, 6 October 2026). Claude Code.

Writes inventory/review/pete-knight-profile-draft-2026-10-06.json (read by
scripts/import/build_knight_profile_2026_10_06.php) and the .md beside it for reading.
The body carries {KEY} markers; they are numbered here by first appearance, one [n] per
note, so a note cited twice keeps its number.

Every quotation below was read in the source named, on 6 October 2026: the mirror pages
from the Reggie mirror (latin-1), the outside sources from the copies saved in
inventory/sources/pete-knight-2026-10-06/ (manifest.json there), the district figures from
templates/_data/valley-districts.json. No quotation joins two clauses with an ellipsis.
Run on the host: python3 scripts/import/draft_knight_profile_2026_10_06.py
"""
import json, os, re

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..')
OUT = os.path.join(ROOT, 'inventory', 'review', 'pete-knight-profile-draft-2026-10-06')

NOTES = {
    'NM': 'Leon Worden, "Newsmaker of the Week: State Sen. William J. \'Pete\' Knight," The Signal, Sunday, April 25, 2004, "(Television interview conducted April 1, 2004)," archive document #31412 (legacy page /scvhistory/signal/newsmaker/sg042504.htm). The editor\'s note above it: "This was Pete Knight\'s final television interview. On April 7, 2004, he was diagnosed with acute myelogenous leukemia. He died May 7, 2004." The introduction: "has represented most of the Santa Clarita Valley in the Legislature since 1992." Knight: "not so much as opposition to gay marriage as the fact that, I don\'t want to change the definition of marriage"; "I got a vote on the Senate floor, and it was a tie vote, 20-20"; "And who was the president of the Senate, but Lt. Gov. Gray Davis. He came in and voted against it"; "So we established the Prop. 22 Legal Defense and Education Fund, a nonprofit corporation, if you will"; "George Runner is going to be elected to the 17th Senate District in my stead." The boxed "Knight\'s Military Background" printed beside the interview: "To date he has more than 7,000 flying hours including 5,000 in jet aircraft."',
    'SIGOBIT': 'Leon Worden, "Sen. Pete Knight Succumbs to Leukemia," The Signal, Sunday, May 9, 2004, legacy page /scvhistory/sg050904.htm (not yet a record in the archive): "William J. "Pete" Knight, 74, of Palmdale, died about 7:30 p.m. at City of Hope National Medical Center in Duarte"; "Knight was diagnosed with the disease April 7 and took a formal leave of absence from office April 12"; "He represented most of the Santa Clarita and Antelope valleys in the Legislature since 1992 when he was elected to the Assembly"; "Knight achieved statewide attention when he authored Proposition 22"; "Because his death followed the March primary, his seat will remain vacant until a successor is elected in November"; "George Runner, who succeeded Knight in the Assembly"; "Knight gave Smyth his first real job out of college in 1994. Smyth stayed until 2000"; "He logged more than 7,000 flying hours, tested more than 100 experimental aircraft and flew 253 missions over Vietnam."',
    'LEGIS': 'His two terms are the archive\'s office holdings #29338 (Assembly, 36th District, 7 December 1992 to 2 December 1996) and #29357 (State Senate, 17th District, 2 December 1996 to 7 May 2004). California Secretary of State, Statements of Vote: 3 November 1992, 36th Assembly District, "William J \'Pete\' Knight" 79,718 votes, 58.18 per cent, https://elections.cdn.sos.ca.gov/sov/1992-general/assemblymember.pdf; 8 November 1994, 36th Assembly District, https://elections.cdn.sos.ca.gov/sov/1994-general/assemblymember.pdf; 5 November 1996, 17th State Senate District, https://elections.cdn.sos.ca.gov/sov/1996-general/state-senator.pdf; 7 November 2000, 17th State Senate District, 172,723 votes, 64.4 per cent, https://elections.cdn.sos.ca.gov/sov/2000-general/sen.pdf. Secretary of the Senate, Record of Members of the Assembly, 1849 to 2026, https://secretary.senate.ca.gov/media/79: "Knight, William J.", Los Angeles, 1993 to 1996. Record of State Senators, 1849 to 2026, https://secretary.senate.ca.gov/media/88: "Knight, William J. "Pete"", Inyo, Kern, Los Angeles and San Bernardino, 1997 to 2004; note 113: "Died in office May 7, 2004. Succeeded by George Runner."',
    'DIST': 'The archive\'s count of the valley\'s people by district, templates/_data/valley-districts.json, Assembly and State Senate, "1991 lines, drawn by the court\'s Special Masters": the 36th Assembly District and the 17th Senate District each held "83.7%" of the valley, 171,805 people at the 2000 Census, counted from census blocks assigned to districts in the Statewide Database\'s block file; the area each held: "The City of Santa Clarita as it then stood, Agua Dulce and the unincorporated land between them"; the 17th also: "joined to the Antelope Valley, Inyo County and parts of Kern and San Bernardino counties." The rest of the valley, "Castaic, Val Verde and Stevenson Ranch", 16.3 per cent, was in the 38th Assembly and 19th Senate districts. An earlier pass (inventory/review/legislative-districts-2026-10-04.md) gave 84 per cent, and that file marks its figures as superseded.',
    'SMYTH': 'City of Santa Clarita, biography of Mayor Cameron Smyth, 2005, on the archive page /scvhistory/sc0010.htm: "After the 1994 General Election, he was hired by state Assemblyman "Pete" Knight and in 1996 Smyth managed Knight\'s victorious state Senate Campaign"; "Upon winning the election, Senator Knight promoted Smyth to Deputy Chief of Staff, a position he held for the next four years." Leon Worden, "Curious about homeless, City Council hopefuls," The Signal, 19 November 1997, archive article #12404: "Cameron Smyth, aide to Senator Pete Knight."',
    'VETS': 'City of Santa Clarita, on the archive\'s photograph "Future Veterans Historical Plaza Site, 1998," #4951 (/scvhistory/lw3135.htm): "The City Council led an effort that included the support of then Assembly-member George Runner and State Senator Pete Knight, to secure $250,000 in State funding through the Department of Veterans Affairs for the land acquisition of one-half acre for this project." The same passage says the effort began "In 2000".',
    'USAF': 'James Young, Chief Historian, Air Force Flight Test Center, Edwards Air Force Base, biography of Knight written in October 1999, published by NASA at https://www.nasa.gov/history/x15/knight.html (read 6 October 2026) and reproduced on the archive page /scvhistory/eafb100317.htm: "Pete Knight grew up in Noblesville, Indiana, and enlisted in the USAF in 1951"; "After completing his undergraduate education with a degree in aeronautical engineering from the Air Force Institute of Technology in 1958, he attended the USAF Test Pilot School at Edwards AFB where he graduated later that same year"; "While climbing through 107,000 feet at Mach 4.17 on June 29, 1967, he suffered a total electrical failure and all onboard systems shutdown"; "he glided down to a safe emergency landing at Mud Lake, Nevada. For his remarkable feat of airmanship that day, he earned a Distinguished Flying Cross"; "he piloted the modified X-15A-2 to a speed of 4,520 mph (Mach 6.7)"; "Knight also became one of only five pilots to earn astronaut\'s wings by flying an airplane in space when he climbed to 280,500 feet on October 17, 1967"; "he went to Southeast Asia in 1968 where he completed a total of 253 combat sorties in the F-100"; "he returned to Edwards AFB as vice commander of the AFFTC in 1979"; "After 32 years of service and more than 6,000 hours in the cockpits of more than 100 different aircraft, he retired from the USAF in 1982"; "In 1984, he was elected to the city council of Palmdale, California, and, four years later became the city\'s first elected mayor." 280,500 feet is about 53 miles, or 85.5 kilometres.',
    'NASAFS': 'NASA Dryden Flight Research Center (now Armstrong), X-15 fact sheet, undated as reproduced on the archive page /scvhistory/eafb100317.htm: "The 12 pilots of NASA, the Air Force, Navy, and North American Aviation who flew in the program are listed in the order of their first flights"; "William J. Knight, USAF, 16 flights"; "Unofficial world speed record; X-15 No. 2; Oct. 3, 1967; pilot, William Knight, USAF"; "a record for winged aircraft that still stands."',
    'AVPBIO': 'Norman Shoaf, "Pete Knight\'s Record," Antelope Valley Press, May 9, 2004, legacy page /scvhistory/avp050904b.htm (not yet a record in the archive): "1950: Knight is drafted into the Air Force"; "1988: Knight becomes Palmdale\'s first elected mayor. He is re-elected to a second two-year term in 1990, serving until 1992"; "earned his astronaut wings on a trip of more than 50 miles above the earth\'s surface."',
    'LATOBIT': 'Richard Fausset, "Former Test Pilot Was Foe of Gay Marriage," Los Angeles Times, May 9, 2004, legacy page /scvhistory/lat050904.htm (not yet a record in the archive): "Knight joined the Air Force in 1951"; "When he retired in 1982 as a colonel, he had flown 253 combat missions in Southeast Asia and more than 6,000 hours in about 100 planes"; "In 1984, Knight was elected to the City Council in Palmdale"; "He became its mayor four years later"; "Knight was best known as the author of Proposition 22"; "the elder Knight fought the city\'s efforts in court"; "his estranged son traveled from his home in Baltimore to marry his partner in San Francisco\'s City Hall"; "David Knight told The Times in March", in the words "I love my father dearly and I miss him."',
    'LAT96': 'Nancy Hill-Holtzman, "Foe of Gay Marriages Says His Son Is Homosexual," Los Angeles Times, September 11, 1996, https://www.latimes.com/archives/la-xpm-1996-09-11-me-42738-story.html, read 6 October 2026: "Republican Assemblyman William J. "Pete" Knight, author of a bill that would have barred California from recognizing gay marriages performed in other states, said Tuesday that one of his sons is a homosexual"; "the sexual orientation of his middle son, David"; "In an interview Tuesday, Knight (R-Palmdale) also acknowledged having a gay younger brother who died last summer at 60 of complications of AIDS"; "Of his younger brother who died of AIDS, Knight said simply, "We never talked about it.""; "Knight\'s bill ultimately died in the Legislature."',
    'LW96': 'Leon Worden, "Same-sex marriage? Think it through!", The Signal, July 17, 1996, archive article #12446: "This isn\'t at all what Pete Knight had in mind when he wrote those two little sentences a few months ago"; "Our local Assemblyman wanted to make sure California doesn\'t recognize same-sex marriages that are consecrated here or anywhere else."',
    'PROP': 'In re Marriage Cases (2008) 43 Cal.4th 757, California Supreme Court, S147999, filed May 15, 2008: "Section 308.5, an initiative statute submitted to the voters of California as Proposition 22 at the March 7, 2000, primary election and approved by the voters at that election, provides in full: "Only marriage between a man and a woman is valid or recognized in California."" Legislative Analyst\'s Office, "Proposition 22: Limit on Marriages," Initiative Statute, https://lao.ca.gov/ballot/2000/22_03_2000.html. California Secretary of State, Statement of Vote, Primary Election, March 7, 2000, certified by Secretary of State Bill Jones on April 15, 2000 (the Statewide Database\'s copy, https://www.statewidedatabase.org/pub/data/REPORTS/SOV/2000/P00/Complete_P00.pdf): Proposition No. 22, "Limit On Marriage," State Totals, For 4,618,673 (61.40%), Against 2,909,370 (38.60%).',
    'COURT': 'In re Marriage Cases (2008) 43 Cal.4th 757, filed May 15, 2008: "because the limitation of marriage to opposite-sex couples imposed by section 308.5 can have no constitutionally permissible effect in light of the constitutional conclusions set forth in this opinion, that provision cannot stand." Senate Floor Analysis of SB 1306 (Leno), April 30, 2014: "On May 15, 2008, the California Supreme Court, in a 4-3 decision, struck down as unconstitutional the California statutes enacted by Proposition 22 in 2000 limiting marriage to a man and a woman." SB 1306, whose title includes "to repeal Section 308.5 of, and to repeal and add Section 308 of, the Family Code, relating to marriage," was "Chaptered by Secretary of State. Chapter 82, Statutes of 2014." on July 7, 2014 (bill status, https://www.leginfo.ca.gov/pub/13-14/bill/sen/sb_1301-1350/sb_1306_bill_20140711_status.html). The same words were put into the state Constitution by Proposition 8 in November 2008; that is a different measure and is not his.',
    'RUNNER': 'George Runner\'s office holdings #29340 (Assembly, 36th District, 2 December 1996 to 2 December 2002) and #29359 (State Senate, 17th District, 6 December 2004 to 21 December 2010), from the Secretary of State\'s Statements of Vote of 5 November 1996 (Assembly) and 2 November 2004 (State Senate) and the Secretary of the Senate\'s Records of Members. Record of State Senators, note 113, on Knight: "Succeeded by George Runner."',
    'KIN': 'SCVHistory.com, the introduction to its page of Edwards Air Force Base\'s film of 3 October 2017, /scvhistory/eafb100317.htm: "Pete Knight is the father of U.S. Rep. Steve Knight, R-Palmdale." Richard Fausset, Los Angeles Times, May 9, 2004 (/scvhistory/lat050904.htm): "Besides his son David, Knight is survived by his wife, Gail; sons Peter and Steven; four stepchildren, and 15 grandchildren." JoinCalifornia, "Steve Knight," https://www.joincalifornia.com/candidate/13281, read 6 October 2026: "Son of Pete Knight."',
    'STEVE': 'Steve Knight\'s office holdings #29363 (State Senate, 21st District, 3 December 2012 to 5 January 2015) and #29376 (United States House of Representatives, 25th District, 3 January 2015 to 3 January 2019), from the Secretary of State\'s Statements of Vote and the Secretary of the Senate\'s Record of State Senators; the 21st and the 25th were the districts holding most of the valley under the 2011 lines (templates/_data/valley-districts.json).',
}

BODY = [
    'On 1 April 2004 State Senator William J. "Pete" Knight sat for the Signal\'s "Newsmaker of the Week" with its City Editor, Leon Worden, for broadcast on SCVTV. It was his last television interview: six days later he learned he had acute myelogenous leukemia, and he died on 7 May 2004, in office.{NM}{SIGOBIT}{LEGIS} Asked how it felt that most Californians would remember him for opposing gay marriage, he said that he did not want "to change the definition of marriage"; he went on to Proposition 22, which he had written, the lawsuits his foundation was bringing in its defence, term limits, and the speed record he still held.{NM}',
    'Knight represented most of the Santa Clarita Valley in the Legislature for eleven and a half years: in the Assembly for the 36th District from December 1992 to December 1996, and in the State Senate for the 17th District from December 1996 until his death.{LEGIS} Under the 1991 district lines both districts held the City of Santa Clarita as it then stood, Agua Dulce and the land between them, 83.7 per cent of the valley\'s people by the archive\'s count from the 2000 census; the Senate district joined them to the Antelope Valley, Inyo County and parts of Kern and San Bernardino counties.{DIST} He lived in Palmdale.{SIGOBIT} Cameron Smyth, later a Santa Clarita councilman and assemblyman, worked for him from 1994 to 2000, managed his Senate campaign in 1996 and was his deputy chief of staff.{SMYTH}{SIGOBIT} In 2000 he and Assemblyman George Runner supported the City Council\'s effort to secure $250,000 in state money toward the land for the Veterans Historical Plaza in Newhall.{VETS}',
    'Before politics he was an Air Force test pilot. Born in Noblesville, Indiana, on 18 November 1929, he joined the Air Force in 1951 by the account of its Flight Test Center\'s historian and of the Los Angeles Times (1950, drafted, in the Antelope Valley Press\'s), and became a test pilot at Edwards Air Force Base in 1958.{USAF}{LATOBIT}{AVPBIO} He was one of the twelve men who flew the X-15 rocket plane, and flew it sixteen times.{NASAFS} On 29 June 1967, climbing through 107,000 feet, the aircraft lost all electrical power, and he glided it down to an emergency landing on Mud Lake, Nevada, for which he earned the Distinguished Flying Cross.{USAF} On 3 October 1967 he flew the modified X-15A-2 to 4,520 miles an hour, Mach 6.7, which NASA\'s fact sheet calls a record for winged aircraft that still stands; on 17 October he took the X-15 to 280,500 feet, more than 50 miles up, and earned astronaut\'s wings.{USAF}{NASAFS}{AVPBIO} From 1968 he flew 253 combat sorties in Southeast Asia in the F-100.{USAF} He returned to Edwards as vice commander of the Flight Test Center in 1979 and retired as a colonel in 1982 after thirty-two years, with more than 6,000 flying hours in more than 100 types of aircraft by the historian\'s count, and more than 7,000 by the Signal\'s.{USAF}{LATOBIT}{NM}{SIGOBIT} He was elected to the Palmdale City Council in 1984 and became the city\'s first elected mayor in 1988.{USAF}{LATOBIT}{AVPBIO}',
    'In 1996, in the Assembly, he wrote a bill to bar California from recognizing same-sex marriages made in other states; it died in the Legislature, and by his own account a second attempt failed in the Senate on a tie vote of 20 to 20 that Lieutenant Governor Gray Davis broke against it.{LAT96}{LW96}{NM} He then took the question to the voters as an initiative, Proposition 22, which added to the Family Code the words that only marriage between a man and a woman was valid or recognized in California. It passed on 7 March 2000 with 61.4 per cent of the vote.{PROP} The Los Angeles Times wrote at his death that he was best known as its author.{LATOBIT}{SIGOBIT} After it passed he set up the Proposition 22 Legal Defense and Education Fund to defend it in court.{NM} In 2008 the California Supreme Court held the law unconstitutional, and in 2014 the Legislature repealed it.{COURT}',
    'In September 1996, after that bill had died, Knight told the Los Angeles Times that his middle son, David, was gay, and that a younger brother had died of complications of AIDS the summer before; of his brother he said, "We never talked about it."{LAT96} In March 2004, while his father was in court against San Francisco\'s marriage licences, David Knight married his partner at San Francisco City Hall, and told the Times, "I love my father dearly and I miss him."{LATOBIT}',
    'He was due to leave the Senate at the end of 2004 under term limits, and said in the interview that George Runner, who had succeeded him in the Assembly in 1996, would be elected to the 17th District in his place. The seat stayed empty from his death until Runner took it in December 2004.{NM}{SIGOBIT}{RUNNER} His son Steve Knight later represented the valley in the State Senate, for the 21st District, from 2012 to 2015, and in Congress, for the 25th District, from 2015 to 2019.{KIN}{STEVE}',
]

order = []
for p in BODY:
    for k in re.findall(r'\{([A-Z0-9]+)\}', p):
        if k not in order:
            order.append(k)
unused = set(NOTES) - set(order)
if unused:
    raise SystemExit('notes never cited: ' + ', '.join(sorted(unused)))
num = {k: i + 1 for i, k in enumerate(order)}
body = '\n\n'.join(re.sub(r'\{([A-Z0-9]+)\}', lambda m: f'[{num[m.group(1)]}]', p) for p in BODY)
footnotes = [{'number': str(num[k]), 'key': k, 'note': NOTES[k]} for k in order]
for t in [body] + [f['note'] for f in footnotes]:
    if '—' in t:
        raise SystemExit('an em dash in our own text: ' + t[:80])

kin_note = ('Pete Knight, his father, also held office for the valley, in the Assembly and the State Senate (office holdings #29338 and #29357). ' + NOTES['KIN'])
draft = {
    'drafted': '2026-10-06', 'draftedBy': 'scripts/import/draft_knight_profile_2026_10_06.py, Claude Code',
    'person': {'id': 29314, 'title': 'Pete Knight'},
    'body': body, 'footnotes': footnotes,
    'fields': {
        'bodyAuthorship': 'editorial-2026',
        'birthDate': 'November 18, 1929', 'birthDateEdtf': '1929-11-18', 'birthEvidence': 'retrospective', 'birthplace': 'Noblesville, Indiana',
        'occupation': 'Air Force test pilot; state assemblyman and senator',
        'wikidataId': 'Q974431', 'personWikipediaUrl': 'https://en.wikipedia.org/wiki/William_J._Knight',
        'aliasesAdd': ['Wm. J. "Pete" Knight', 'Sen. Pete Knight'],
        'rolesAdd': [18313],
        'relatedPersonsAdd': [18747],
    },
    'kinship': {'child': 29328, 'parent': 29314, 'field': 'childOf', 'footnoteOnChild': kin_note},
    'holdingNotes': {
        '29338': 'Succeeded in the 36th District by George Runner, elected on 5 November 1996 (Secretary of State, Statement of Vote, 5 November 1996, State Assembly; office holding #29340). Leon Worden, The Signal, May 9, 2004: "George Runner, who succeeded Knight in the Assembly."',
        '29357': 'Record of State Senators, 1849 to 2026, note 113: "Died in office May 7, 2004. Succeeded by George Runner." The seat was vacant from his death until Runner took office on 6 December 2004 (office holding #29359); The Signal, May 9, 2004: "Because his death followed the March primary, his seat will remain vacant until a successor is elected in November."',
    },
}
json.dump(draft, open(OUT + '.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=1)

md = ['# Pete Knight #29314: the profile draft, 6 October 2026', '',
      'For Nathan to read before the loader is applied. Body first, then the notes as they will be numbered. Nothing here is written to Craft; the loader (scripts/import/build_knight_profile_2026_10_06.php) reads the .json beside this file.', '',
      '## Body', '', body, '', '## Notes', '']
md += [f"{f['number']}. {f['note']}" for f in footnotes]
md += ['', '## Other fields', '']
md += [f'- {k}: {v}' for k, v in draft['fields'].items()]
md += ['', '## Kinship', '', f"Steve Knight #29328 childOf Pete Knight #29314, with this note added to Steve Knight's record (where the page's test, publicKin, looks for it):", '', '> ' + kin_note, '',
       '## Notes added to the office holdings', '']
md += [f'- #{k}: {v}' for k, v in draft['holdingNotes'].items()]
MIRROR = [
    '## What the mirror holds on him',
    '',
    'Searched 6 October 2026 with Python reading every .htm, .html, .txt, .xml and .js file in /Volumes/Reggie/SCVHistory/scvhistory.com as latin-1 (146,750 files), for "Pete Knight" and its punctuated forms, "Knight, R-Palmdale", "Senator Knight", "Sen. Knight", "Assemblyman Knight", "X-15", "Knight Initiative", "Proposition 22", "Prop. 22", "Steve Knight", "Knight High"; and the text index storage/runtime/pc/index.jsonl (33,690 pages, captions included). Pages about the rodeo rider Pete Knight of Alberta (lw2096, lw3531, lw3668) and the 1998 Proposition 227 columns are not him.',
    '',
    '| Page | What it holds | In Craft |',
    '|---|---|---|',
    '| /scvhistory/signal/newsmaker/sg042504.htm | His final television interview, Newsmaker of the Week, taped 1 April 2004, printed 25 April 2004; sidebars "Knight\'s Military Background" and "Official Biography"; photographs gif/sg042504.jpg ("Pete Knight on April 1, 2004") and gif/sg042504b.jpg ("Pete Knight, 1965") | document #31412 (imported today); the 2004 photograph is asset #31240 |',
    '| /scvhistory/sg050904.htm | Leon Worden, "Sen. Pete Knight Succumbs to Leukemia," The Signal, 9 May 2004: obituary with Runner, Smyth, Kelly, McKeon and Burton quoted | not held |',
    '| /scvhistory/lat050904.htm | Richard Fausset, "Former Test Pilot Was Foe of Gay Marriage," Los Angeles Times, 9 May 2004: obituary; career, Proposition 22, son David, survivors (sons Peter and Steven) | not held |',
    '| /scvhistory/avp050904.htm | Dennis Anderson and Heather Lake, "So Long to Hero Pete Knight," Antelope Valley Press, 9 May 2004: obituary | not held |',
    '| /scvhistory/avp050904b.htm | Norman Shoaf, "Pete Knight\'s Record," Antelope Valley Press, 9 May 2004: a dated chronology of his life | not held |',
    '| /scvhistory/eafb100317.htm | Edwards Air Force Base film of his 3 October 1967 flight (posted 3 October 2017); the site\'s introduction ("Pete Knight is the father of U.S. Rep. Steve Knight"); James Young\'s 1999 Air Force biography; NASA Dryden\'s X-15 fact sheet | not held |',
    '| /scvhistory/signal/worden/old/lw071796.htm | Leon Worden, "Same-sex marriage? Think it through!", 17 July 1996: Knight\'s 1996 bill, with Knight interviewed | article #12446 |',
    '| /scvhistory/signal/worden/old/lw102396.htm | Leon Worden, "A politician by any other name...", 23 October 1996: "Our current Assemblyman, Pete Knight, is on his way to the State Senate"; the origin of the nickname | article #12358 |',
    '| /scvhistory/signal/worden/old/lw111997.htm | Leon Worden, 19 November 1997: "Cameron Smyth, aide to Senator Pete Knight" | article #12404 |',
    '| /scvhistory/signal/newsmaker/sg112303.htm | Newsmaker of the Week, Scott Edwards and Al Carbonara, 23 November 2003: critics of Knight and Proposition 22 | not held |',
    '| /scvhistory/sc0010.htm | City of Santa Clarita biography of Cameron Smyth (2005): hired by Knight after the 1994 election, his 1996 campaign manager and deputy chief of staff | not held |',
    '| /scvhistory/lw3135.htm and /scvhistory/sc1711.htm | City of Santa Clarita text: Knight and Runner backed $250,000 in state money for the Veterans Historical Plaza | lw3135 is photograph #4951; sc1711 not held |',
    '| /oldtownnewhall/gazette/gazette1201-vets.htm | Old Town Newhall Gazette, January-February 2006: donations for a memorial plaque to Knight at the Veterans Plaza | article #12629 |',
    '| /oldtownnewhall/rioux/rr102096.htm | Rioux column, 20 October 1996: "GAYS vs. PETE KNIGHT" in a list of local contests | article #12804 |',
    '| /scvhistory/lw2758.htm | Photograph, 1994 campaign rally in Valencia for Gov. Pete Wilson and Rep. Buck McKeon: "then-Assemblyman William J. \\"Pete\\" Knight" partially visible | not held |',
    '| /scvhistory/lw2102b.htm | Photograph, Herb Jeffries\' Walk of Western Stars induction, 2001: "Patty Kelly, representing State Sen. William J. \\"Pete\\" Knight, R-19th" (the page says 19th; he held the 17th) | not held |',
    '| /scvhistory/files/scvhs_collectionlist_20131114 (flipbook, search page 447) | SCV Historical Society collection list, item HS3110: a print of the 69th annual Fourth of July parade in Old Town Newhall, a convertible "labelled on the side it reads Pete Knight Assemblyman" | not held (the print is in the Society\'s collection) |',
    '| /scvhistory/timeline.htm | Chronology: his 1929 birth, the 3 October 1967 flight, 1 April 2004 ("tapes SCVTV \\"Newsmaker\\" show on way home"), 7 May 2004 death | index page |',
    '| /scvhistory/people.htm, news.htm, obits.htm, signal/newsmaker/index.htm | Index entries pointing at the pages above ("Episode 32 / State Senator Pete Knight") | index pages |',
    '',
    'The Historical Society minutes of 2010 to 2017 (flipbook scvhs20102017minutes) mention "Senator Knight" twice: that is Steve Knight and the St. Francis Dam bill, not his father.',
    '',
]
md += MIRROR
open(OUT + '.md', 'w', encoding='utf-8').write('\n'.join(md) + '\n')
print(f'{len(body.split())} words, {len(footnotes)} notes; written {os.path.relpath(OUT)}.json and .md')
