/**
 * Three follow-ups of 29 September 2026, Nathan's decisions after the schools
 * apply and the Star Oil build.
 *
 * 1. Newhall Elementary School #15958: ncesId 062718009956 matches no school in
 *    the NCES directory for 2015 or 2022-23. The directory's Newhall Elementary,
 *    Newhall School District, K-6, is 062718004095. The record takes that, and
 *    a correcting note says what it held before and why it changed.
 * 2. "Hart Union High School" moves from William S. Hart High School #16052 to
 *    the William S. Hart Union High School District: it is the district's name.
 * 3. California Star Oil Works #16039 gets a featured image from the four
 *    photographs of the refinery the archive holds: #3901, "Pioneer Oil
 *    Refinery ~1930" (lw2497), the whole works, stills, chimneys and boiler.
 *    #3031 is the same view and sharper, but it is a postcard lettered "First
 *    Oil Refinery 1875", a third founding date the body would then have to
 *    answer in its own header. The file Nathan first supplied was generated by
 *    Adobe Firefly and was deleted.
 *
 * Each change checks the current value first. Idempotent. Dry run by default.
 * Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/fix_schools_and_csow_image.php'))"
 */

use craft\elements\Entry;
use craft\elements\Asset;

$APPLY = false;
if ($APPLY) { echo 'APPLY IS ON, this will write to the database' . PHP_EOL; }
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL . str_repeat('=', 78) . PHP_EOL;

$NEWHALL_EL = 15958; $OLD_NCES = '062718009956'; $NEW_NCES = '062718004095';
$HART_HIGH = 16052; $ALIAS = 'Hart Union High School';
$CSOW = 16039; $PHOTO = 3901; $ASSET = 13676; $ASSET_FILE = 'lw2497.jpg';
$get = fn($id) => Entry::find()->id($id)->status(null)->one();
$lines = fn($v) => array_values(array_filter(array_map('trim', preg_split('~[\n]~', (string)$v))));
$ops = []; $done = []; $refused = [];

/* 1 */
$n = $get($NEWHALL_EL);
$cur = trim((string)$n->ncesId);
if ($n->title !== 'Newhall Elementary School') { $refused[] = "#$NEWHALL_EL is not Newhall Elementary School"; }
elseif ($cur === $NEW_NCES) { $done[] = 'Newhall Elementary already carries ' . $NEW_NCES; }
elseif ($cur !== $OLD_NCES) { $refused[] = "Newhall Elementary ncesId is $cur, not $OLD_NCES"; }
else {
    echo "1. #$NEWHALL_EL Newhall Elementary School: ncesId $OLD_NCES -> $NEW_NCES, with a correcting note" . PHP_EOL;
    $ops[] = [function () use ($get, $NEWHALL_EL, $OLD_NCES, $NEW_NCES) {
        $n = $get($NEWHALL_EL);
        $n->setFieldValue('ncesId', $NEW_NCES);
        $notes = array_values(array_filter($n->editorNotes, fn($r) => trim((string)($r['note'] ?? '')) !== ''));
        $notes[] = ['heading' => 'Correction: NCES identifier', 'position' => 'bottom',
            'note' => "Until 29 September 2026 this record carried NCES ID $OLD_NCES, which matches no school in the NCES Common Core of Data directory for 2015 or 2022-23. The directory's Newhall Elementary, in the Newhall School District, grades K-6, is $NEW_NCES (https://nces.ed.gov/ccd/schoolsearch/school_detail.asp?ID=$NEW_NCES), and the record now carries that."];
        $n->setFieldValue('editorNotes', $notes);
        return Craft::$app->getElements()->saveElement($n) ? '' : 'save failed';
    }, fn() => trim((string)$get($NEWHALL_EL)->ncesId) === $NEW_NCES ? '' : 'Newhall Elementary ncesId did not change', 'Newhall Elementary NCES'];
}

/* 2 */
$h = $get($HART_HIGH);
$d = Entry::find()->section('organizations')->status(null)->ncesId('0642510')->one();
if (!$d) { $refused[] = 'the Hart district record is missing (apply add_school_structure.php first)'; }
else {
    $hA = $lines($h->orgAliases); $dA = $lines($d->orgAliases);
    $onSchool = in_array($ALIAS, $hA, true); $onDistrict = in_array($ALIAS, $dA, true);
    if (!$onSchool && $onDistrict) { $done[] = 'the alias is already on the district'; }
    else {
        echo "2. \"$ALIAS\": " . ($onSchool ? "off #$HART_HIGH {$h->title} (keeps " . implode(' / ', array_diff($hA, [$ALIAS])) . ')' : 'not on the school') . ", onto #{$d->id} {$d->title}" . PHP_EOL;
        $ops[] = [function () use ($get, $HART_HIGH, $d, $ALIAS, $lines) {
            $h = $get($HART_HIGH);
            $h->setFieldValue('orgAliases', implode("\n", array_values(array_diff($lines($h->orgAliases), [$ALIAS]))));
            if (!Craft::$app->getElements()->saveElement($h)) { return 'school save failed'; }
            $dd = $get($d->id);
            $dA = $lines($dd->orgAliases);
            if (!in_array($ALIAS, $dA, true)) { $dd->setFieldValue('orgAliases', implode("\n", array_merge($dA, [$ALIAS]))); }
            return Craft::$app->getElements()->saveElement($dd) ? '' : 'district save failed';
        }, fn() => (!in_array($ALIAS, $lines($get($HART_HIGH)->orgAliases), true) && in_array($ALIAS, $lines($get($d->id)->orgAliases), true)) ? '' : 'the alias did not move', 'Hart alias moved'];
    }
}

/* 3 */
$o = $get($CSOW); $p = $get($PHOTO); $a = Asset::find()->id($ASSET)->one();
if (!$o || $o->title !== 'California Star Oil Works') { $refused[] = "#$CSOW is not California Star Oil Works"; }
elseif (!$p || $p->title !== 'Pioneer Oil Refinery ~1930' || !$a || $a->filename !== $ASSET_FILE) { $refused[] = "photograph #$PHOTO or its image $ASSET_FILE is not as seen"; }
elseif ($cur3 = $o->featuredImage->one()) { if ($cur3->id === $ASSET) { $done[] = 'Star Oil already features lw2497'; } else { $refused[] = 'Star Oil already features #' . $cur3->id . ' ' . $cur3->filename; } }
else {
    echo "3. #$CSOW California Star Oil Works: featuredImage -> asset #$ASSET $ASSET_FILE, the image of photograph #$PHOTO \"{$p->title}\"" . PHP_EOL;
    $ops[] = [function () use ($get, $CSOW, $ASSET) { $o = $get($CSOW); $o->setFieldValue('featuredImage', [$ASSET]); return Craft::$app->getElements()->saveElement($o) ? '' : 'save failed'; },
        fn() => ($get($CSOW)->featuredImage->one()->id ?? null) === $ASSET ? '' : 'featuredImage is not lw2497', 'Star Oil featured image'];
}

echo PHP_EOL . 'ALREADY DONE: ' . ($done ? implode('; ', $done) : 'none') . PHP_EOL . 'REFUSED: ' . ($refused ? implode('; ', $refused) : 'none') . PHP_EOL;
echo 'SUMMARY: ' . count($ops) . ' change(s).' . PHP_EOL;
if (!$APPLY) { echo str_repeat('=', 78) . PHP_EOL . 'nothing was written. Set $APPLY = true to apply.' . PHP_EOL; return; }
if ($refused) { echo 'REFUSING: resolve the refusals first' . PHP_EOL; return; }
if (!$ops) { echo 'nothing to do; a second run is a no-op' . PHP_EOL; return; }
$short = [];
foreach ($ops as [$do, $check, $label]) { $e = $do(); if ($e) { $short[] = "$label: $e"; continue; } $b = $check(); if ($b) { $short[] = "$label: $b"; } }
echo 'READ-BACK ' . ($short ? 'SHORT: ' . implode('; ', $short) : 'OK: ' . implode(', ', array_map(fn($o) => $o[2], $ops))) . PHP_EOL;
$applyLog = require \Craft::getAlias('@root') . '/scripts/import/_apply_log.php';
$applyLog('fix_schools_and_csow_image.php', count($ops), $short ? 'SHORT: ' . implode('; ', $short) : 'verified', implode(', ', array_map(fn($o) => $o[2], $ops)));
if ($short) { throw new \RuntimeException('fix_schools_and_csow_image: ' . implode('; ', $short)); }
