/**
 * What SB 634 did (inventory/review/sb634-consolidation-2026-10-04.md; Nathan, 4 October 2026: "Retire the Water Division
 * record, redirect it, and list it in the removed-records registry. Keep anything it held that the other records lack.
 * Then correct every place we said four bodies merged"; "All three get historical marks and all three sit under SCV Water as
 * predecessors").
 * The statute (Stats. 2017, ch. 833) reorganized two public bodies, the Castaic Lake Water Agency and the Newhall County Water
 * District, into the Santa Clarita Valley Water Agency, their successor. The Santa Clarita Water Division was the Castaic Lake
 * agency's retail division, with no separate existence; the Valencia Water Company was a private company whose stock the
 * agency had owned since December 2012, not a party to the reorganization, which the act directed the new agency to dissolve.
 *  1. Santa Clarita Water Division (#29567) retired: what it held goes into the Castaic Lake agency's text (the Bonelli
 *     companies, the 1999 purchase with its court date, the division); soft-deleted, redirected to the agency, registered.
 *  2. Valencia Water Company: its text rewritten from the statute and the court record; owned by the agency (parent), its
 *     assets passed to SCV Water on its dissolution (succeededBy), and it stays among SCV Water's predecessors as Nathan
 *     decided, its page saying it was not a party to the reorganization.
 *  3. Every "four bodies merged" corrected: SCV Water (#402), the consolidation event (#27712), the Newhall district (#27534),
 *     the Castaic Lake agency (#26563), Scott Wilk (#335, an unsourced import, the paragraph replaced and its unsourced claim of
 *     savings dropped). The footnotes quoting SCV Water's "merged three water agencies" give way to the statute.
 *  4. SCV Water: predecessors the Castaic Lake agency, the Newhall district and the Valencia company; its aliases cut to its
 *     own name.
 * Idempotent. Dry run by default. Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/fix_sb634_two_bodies_2026_10_04.php'))"
 */
use craft\elements\Entry;
$APPLY = false;
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL;
$root = \Craft::getAlias('@root'); $el = Craft::$app->getElements();
$STAT = 'Senate Bill 634 (Wilk), Statutes of 2017, chapter 833, approved and filed October 15, 2017, effective January 1, 2018, https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201720180SB634: section 4(a), the Castaic Lake Water Agency and the Newhall County Water District "shall be reorganized into the Santa Clarita Valley Water Agency and shall no longer operate as separate entities or exercise independent functions"; 4(b), the new agency is "the successor to" them; 4(h), the Santa Clarita Water Division is "a retail division of the Castaic Lake Water Agency"; finding 1(e), the agency "is the owner of all of the outstanding stock of Valencia Water Company, which is a private company"; 4(j), the new agency is to authorize the company\'s dissolution by January 31, 2018, to be finished by May 1, 2018.';
$KLAJIC = 'Klajic v. Castaic Lake Water Agency (2001) 90 Cal.App.4th 987, https://static.case.law/cal-app-4th/90/cases/0987-01.json: the agency resolved on August 11, 1999 to condemn the Santa Clarita Water Company\'s stock; a stipulated judgment for $63 million was entered on September 2, and the final order of condemnation, on payment, on September 3, 1999.';
$SCOPE = 'Santa Clarita Organization for Planning and the Environment v. Castaic Lake Water Agency (2016) 1 Cal.App.5th 1084, https://www.courts.ca.gov/opinions/archive/B264284.PDF: the agency\'s board resolved on December 12, 2012 to acquire the Valencia Water Company\'s stock from Newhall Land by eminent domain on a settlement, and the court entered judgment on December 18, 2012; the Court of Appeal upheld the purchase.';
$HIST = 'Santa Clarita Valley Water Agency, "History of SCV Water," https://yourscvwater.com/who-we-are/history, read 4 October 2026: "Valencia Water Company was incorporated on April 7, 1954"; "In 1999, Castaic Lake Water Agency ... acquired the stock of the company and created the Santa Clarita Water Division"; SCV Water is "home to three water divisions: Newhall Water Division, Santa Clarita Water Division, Valencia Water Division."';
$WORDEN98 = 'Leon Worden, "Santa Clarita Water Company Dissolved," on the agency board\'s vote of October 25, 2017, as carried on SCVHistory.com, /scvhistory/clwa102517.htm, dates the takeover of the company\'s assets to August 31, 1998, from the agency\'s 2017 staff memorandum; the court record gives September 1999. The company itself was dissolved on October 31, 2017.';
$VWCREL = 'Santa Clarita Valley Water Agency, "Resolution Dissolving Valencia Water Company," board memorandum of December 29, 2017, as carried on SCVHistory.com, /scvhistory/scvwa010918.htm: the company\'s board approved a plan of dissolution on December 28, 2017, for the new agency\'s board to adopt in January 2018.';
$fn = fn(array $x) => array_map(fn($i, $t) => ['number' => (string)($i + 1), 'note' => $t, 'source' => 'editorial-2026'], array_keys($x), $x);
$get = fn($id) => Entry::find()->id($id)->status(null)->one();
$S = $get(402); $C = $get(26563); $N = $get(27534); $EV = $get(27712); $W = $get(335); $V = Entry::find()->section('organizations')->status(null)->title('Valencia Water Company')->one(); $D = Entry::find()->section('organizations')->status(null)->title('Santa Clarita Water Division')->one();
$bad = []; foreach ([[$S, 'Santa Clarita Valley Water'], [$C, 'Castaic Lake Water Agency'], [$N, 'Newhall County Water District'], [$EV, 'The SCV Water Consolidation'], [$W, 'Scott Thomas Wilk Sr.'], [$V, 'Valencia Water Company']] as [$e, $t]) { if ($e?->title !== $t) { $bad[] = "not $t"; } }
/* the texts */
$C_BODY = "The Castaic Lake Water Agency was the Santa Clarita Valley's wholesale water agency, which bought State Water Project water for the valley's retail water suppliers, governed by an elected board: a director at large and directors for three divisions. Valley voters chose on 24 April 1962 to join the State Water Project, which brought the Upper Santa Clara Valley Water Agency into being; it was renamed the Castaic Lake Water Agency in 1970.[1]\n\nIt became a retailer too. The private Santa Clarita Water Company had grown from the Bonelli family's Bouquet Canyon Water Company of 1949 and Solemint Water Company of 1956. The agency took all its stock for \$63 million by a condemnation judgment entered on the owners' agreement on 3 September 1999, and ran its service as the agency's Santa Clarita Water Division, a retail division with no separate existence, serving parts of the City and the unincorporated land of Saugus, Canyon Country and West Newhall.[2][3][4] In December 2012 it bought all the stock of the Valencia Water Company from Newhall Land, and kept it as a separate company.[5]\n\nOn 1 January 2018 Senate Bill 634 reorganized the agency, with the Newhall County Water District, into the Santa Clarita Valley Water Agency, their successor. Its Santa Clarita Water Division passed to the new agency, which keeps a division of that name, and the act directed the new agency to dissolve the Valencia Water Company.[6][4]";
$C_NOTES = ['Leon Worden, "Gov. Brown Signs Wilk Bill Merging SCV Water Agencies," SCVNews.com, October 15, 2017, as carried on SCVHistory.com, /scvhistory/scvnews101517.htm; "Castaic Lake Water Agency Facility," WA1980, as carried on SCVHistory.com, /scvhistory/wa1980.htm.',
    'Castaic Lake Water Agency, "History & Overview of Santa Clarita Water Co./Division," August 2012, as carried on SCVHistory.com, /scvhistory/clwa_scwd_2012.htm: the Bonelli family\'s Bouquet Canyon Water Company (1949) and Solemint Water Company (1956), merged as the Santa Clarita Water Company; "In 1999, the Castaic Lake Water Agency purchased SCWC, and the name was changed to the Santa Clarita Water Division"; its retail area "includes a portion of the City of Santa Clarita and unincorporated portions of Los Angeles County in the communities of Saugus, Canyon Country and West Newhall."',
    $KLAJIC . ' ' . $WORDEN98, $HIST, $SCOPE, $STAT];
$V_BODY = "The Valencia Water Company, incorporated on 7 April 1954, was the Newhall Land and Farming Company's private water company, regulated by the Public Utilities Commission, and one of the valley's retail water suppliers that bought their state water from the Castaic Lake Water Agency.[1] In December 2012 the agency bought all its stock from Newhall Land, by eminent domain on a settlement: its board resolved on 12 December, and the court entered judgment on 18 December. The company went on as a separate company owned by the agency. The Court of Appeal upheld the purchase in 2016, and the Newhall County Water District's suit over it was among the disputes the two public agencies settled by merging.[2][3]\n\nIt was not a party to the 2018 reorganization. Senate Bill 634 reorganized the Castaic Lake agency and the Newhall district into the Santa Clarita Valley Water Agency, which as the agency's successor became the company's owner, and directed the new agency to dissolve the company and take over its assets. The company's board approved a plan of dissolution on 28 December 2017, the new agency adopted it in January 2018, and the company's assets passed to SCV Water, which keeps a Valencia Water Division.[4][5][1]";
$V_NOTES = [$HIST, $SCOPE, 'Leon Worden, "Gov. Brown Signs Wilk Bill Merging SCV Water Agencies," SCVNews.com, October 15, 2017, as carried on SCVHistory.com, /scvhistory/scvnews101517.htm.', $STAT, $VWCREL];
$EV_P1 = "On 1 January 2018 the valley's public water agencies became one. Senate Bill 634, an act of the State Legislature, reorganized the Castaic Lake Water Agency, the regional wholesaler that bought State Water Project water, and the Newhall County Water District into a new agency, the Santa Clarita Valley Water Agency, SCV Water, as their successor. The Castaic Lake agency's retail Santa Clarita Water Division came with it, as did the Valencia Water Company, whose stock the agency had owned since 2012; the act directed SCV Water to dissolve the company and take over its assets, which was done that January.[1][2]";
$S_OLD1 = "when it took the place of four: the Castaic Lake Water Agency, the Newhall County Water District, the agency's Santa Clarita Water Division and the Valencia Water Company.";
$S_NEW1 = "when Senate Bill 634 reorganized the Castaic Lake Water Agency and the Newhall County Water District into it as their successor. With the Castaic Lake agency came its retail Santa Clarita Water Division and the Valencia Water Company, whose stock it owned; the act directed the new agency to dissolve the company and take over its assets, which it did that January.";
$N_OLD = "Senate Bill 634 merged the district, the Castaic Lake Water Agency and its Santa Clarita Water Division, and the Valencia Water Company into SCV Water, effective 1 January 2018.";
$N_NEW = "Senate Bill 634 reorganized the district and the Castaic Lake Water Agency into SCV Water, their successor, effective 1 January 2018; the Castaic Lake agency's Santa Clarita Water Division and the Valencia Water Company, which it owned, came into SCV Water with it.";
$W_OLDS = 'formally consolidated the Castaic Lake Water Agency, Newhall County Water District, Santa Clarita Water Division, and Valencia Water Company into a single regional agency';
$W_NEW = "Among his most significant legislative achievements for the Santa Clarita Valley was Senate Bill 634, signed by Governor Jerry Brown on October 15, 2017, which on January 1, 2018 reorganized the Castaic Lake Water Agency and the Newhall County Water District into a single regional agency, the Santa Clarita Valley Water Agency. With them came the Castaic Lake agency's Santa Clarita Water Division and its Valencia Water Company, so that one public board now governs the valley's largest water suppliers.";
foreach ([[$S, $S_OLD1], [$N, $N_OLD], [$W, $W_OLDS]] as [$e, $old]) { if ($e && !str_contains((string)$e->body, $old) && !str_contains((string)$e->body, 'reorganized')) { $bad[] = "#{$e->id}: passage not found"; } }
echo "SCWD to retire: " . ($D ? "#{$D->id}" : 'already retired') . PHP_EOL . 'REFUSED: ' . ($bad ? implode(' | ', $bad) : 'none') . PHP_EOL;
if (!$APPLY || $bad) { return; }
$n = 0; $save = function ($e, $v) use ($el, &$n) { $e->setFieldValues($v); if (!$el->saveElement($e)) { throw new \RuntimeException("#{$e->id} " . json_encode($e->getFirstErrors())); } $n++; };
if (!str_contains((string)$C->body, 'condemnation judgment')) { $save($C, ['body' => $C_BODY, 'footnotes' => $fn($C_NOTES), 'dateFounded' => '1962', 'dateFoundedEdtf' => '1962']); }
if (!str_contains((string)$V->body, 'not a party')) { $save($V, ['body' => $V_BODY, 'footnotes' => $fn($V_NOTES), 'hasParentOrg' => true, 'parentOrganization' => [26563], 'succeededBy' => [402], 'dateFounded' => 'April 7, 1954', 'dateFoundedEdtf' => '1954-04-07', 'dateDissolved' => 'January 2018', 'dateDissolvedEdtf' => '2018-01', 'recordProvenance' => 'water_chain_and_edited_marks_2026_10_04.php and fix_sb634_two_bodies_2026_10_04.php, 4 October 2026: owned by the Castaic Lake Water Agency from December 2012; dissolved by SCV Water in January 2018']); }
if (!str_contains((string)$EV->body, 'reorganized')) { $b = (string)$EV->body; $p = strpos($b, "\n\n"); $save($EV, ['body' => $EV_P1 . substr($b, $p), 'footnotes' => $fn([array_column($EV->footnotes, 'note')[0], $STAT])]); }
if (str_contains((string)$S->body, $S_OLD1)) { $notes = array_column($S->footnotes, 'note'); $notes[] = $STAT; $b = str_replace($S_OLD1, $S_NEW1, (string)$S->body); $b = preg_replace('~(their successor\..*?that January\.)~s', '$1[' . count($notes) . ']', $b, 1);
    $b = str_replace('The agency bought the private Santa Clarita Water Company, built from Bill Bonelli\'s Bouquet Canyon (1949) and Solemint (1956) water companies, for $63 million: in 1999 by the agency\'s 2012 history and Leon Worden\'s 2017 report, while the page on the company\'s 2017 dissolution dates the takeover of its assets to August 31, 1998.', 'The agency bought the private Santa Clarita Water Company, built from Bill Bonelli\'s Bouquet Canyon (1949) and Solemint (1956) water companies, in September 1999, taking all its stock for $63 million by a condemnation judgment entered on the owners\' agreement, and ran it as its Santa Clarita Water Division.', $b);
    $save($S, ['body' => $b, 'footnotes' => $fn($notes), 'orgAliases' => "SCV Water\nSanta Clarita Valley Water Agency"]); }
if (str_contains((string)$N->body, $N_OLD)) { $notes = array_column($N->footnotes, 'note'); $notes[] = $STAT; $save($N, ['body' => str_replace($N_OLD . '[1][2]', $N_NEW . '[' . count($notes) . ']', str_replace($N_OLD, $N_NEW, (string)$N->body)), 'footnotes' => $fn($notes)]); }
if (str_contains((string)$W->body, $W_OLDS)) { $save($W, ['body' => preg_replace('~Among his most significant legislative achievements[^\n]*~', $W_NEW, (string)$W->body, 1)]); }
$pre = array_values(array_unique(array_merge([26563, 27534, $V->id]))); if ($S->precededBy->ids() != $pre) { $save($S, ['precededBy' => $pre]); }
if ($D) {
    $regFile = "$root/scripts/import/removed-claims.json"; $reg = json_decode(file_get_contents($regFile), true);
    $reg['removedRecords'][] = ['record' => $D->id, 'title' => $D->title, 'slug' => $D->slug, 'section' => 'organizations', 'why' => 'A retail division of the Castaic Lake Water Agency with no separate existence (SB 634, section 4(h)), not one of the bodies SB 634 reorganized. What it held is in the Castaic Lake Water Agency\'s record, where it now redirects.', 'removed' => '2026-10-04', 'by' => 'scripts/import/fix_sb634_two_bodies_2026_10_04.php (Nathan\'s decision)'];
    file_put_contents($regFile, json_encode($reg, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . "\n");
    if (!$el->deleteElement($D)) { throw new \RuntimeException('retire SCWD'); } $n++;
}
$applyLog = require "$root/scripts/import/_apply_log.php"; $applyLog('fix_sb634_two_bodies_2026_10_04.php', $n, 'verified', 'SB 634 reorganized two bodies: SCWD retired into CLWA, Valencia Water Company rewritten, every four-body passage corrected, SCV Water preceded by three');
echo "done: $n writes" . PHP_EOL;
