/**
 * Real photographs for two records that were waiting for them (Nathan, 29
 * September 2026): Santa Clarita City Hall for The City of Santa Clarita #394,
 * and the Oviatt Library for California State University, Northridge #16347.
 * The images first supplied for both were generated by Adobe Firefly and were
 * deleted; these were found under free licences and chosen for being
 * photographs of the thing, with camera metadata and no content credentials
 * (scan_content_credentials.py: none).
 *
 *   City Hall  Flickr, tkksummers, "Santa Clarita City Hall", 2008, the entrance
 *              and fountain with the lettering; CC BY-SA 2.0. Commons has no
 *              photograph of City Hall.
 *   CSUN       Wikimedia Commons, File:CSUN Central Campus.JPG, Cbl62, the
 *              Oviatt Library; CC BY-SA 3.0.
 *
 * Both licences require attribution, so photoCredit carries it and the licence
 * links from the media page. Dates: the camera's own, which Commons contradicts
 * for CSUN, so both are given.
 *
 * Needs add_license_cc_by_sa_2.php applied for City Hall. Idempotent: an asset
 * is found by filename; a featured image someone set is never replaced. Every
 * value is checked against its field's limit in the dry run. Dry run by
 * default. Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/import_city_hall_csun_photos.php'))"
 */

use craft\elements\Entry;
use craft\elements\Asset;

$APPLY = false;
if ($APPLY) { echo 'APPLY IS ON, this will write to the database' . PHP_EOL; }
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL . str_repeat('=', 78) . PHP_EOL;
$root = \Craft::getAlias('@root');
$PHOTOS = [
    ['record' => 394, 'recordTitle' => 'The City of Santa Clarita', 'file' => 'inventory/incoming/santa-clarita-city-hall-flickr-2600036728.jpg',
     'sha1' => '903f756849a85a01251629b39d308a5718330dbf', 'filename' => 'santa-clarita-city-hall-2008-flickr.jpg',
     'title' => 'Santa Clarita City Hall, 2008', 'alt' => 'The entrance of Santa Clarita City Hall, with its fountain and lettering',
     'fields' => ['creator' => 'tkksummers (Flickr)', 'rightsHolder' => 'tkksummers', 'license' => 'cc-by-sa-2.0', 'provenanceKind' => 'outside',
        'sourceUrl' => 'https://www.flickr.com/photos/tkksummers/2600036728/', 'acquiredDate' => '2026-09-29',
        'dateAsPrinted' => 'June 19, 2008, the camera\'s date', 'dateEdtf' => '2008-06-19~',
        'photoCredit' => 'Photo: tkksummers on Flickr, CC BY-SA 2.0',
        'source' => 'Flickr, tkksummers, "Santa Clarita City Hall," https://www.flickr.com/photos/tkksummers/2600036728/, CC BY-SA 2.0; the original, 3648 x 2736, Kodak EasyShare V1003. Received 29 September 2026, SHA-1 903f756849a85a01251629b39d308a5718330dbf; the stored copy is re-encoded.']],
    ['record' => 16347, 'recordTitle' => 'California State University, Northridge', 'file' => 'inventory/incoming/csun-central-campus-commons.jpg',
     'sha1' => '37fc71d3ce9c8277d19961bb99fa219699afe94d', 'filename' => 'csun-oviatt-library-commons.jpg',
     'title' => 'Oviatt Library, California State University, Northridge', 'alt' => 'The Oviatt Library at California State University, Northridge',
     'fields' => ['creator' => 'Cbl62 (Wikimedia Commons)', 'rightsHolder' => 'Cbl62', 'license' => 'cc-by-sa-3.0', 'provenanceKind' => 'outside',
        'sourceUrl' => 'https://commons.wikimedia.org/wiki/File:CSUN_Central_Campus.JPG', 'acquiredDate' => '2026-09-29',
        'dateAsPrinted' => '2007 or 2008: the camera says January 6, 2007, Commons March 1, 2008', 'dateEdtf' => '[2007-01-06,2008-03-01]',
        'photoCredit' => 'Photo: Cbl62, Wikimedia Commons, CC BY-SA 3.0',
        'source' => 'Wikimedia Commons, File:CSUN Central Campus.JPG, by Cbl62, https://commons.wikimedia.org/wiki/File:CSUN_Central_Campus.JPG, CC BY-SA 3.0; the original, 3264 x 1946, Pentax Optio V10. Received 29 September 2026, SHA-1 37fc71d3ce9c8277d19961bb99fa219699afe94d; the stored copy is re-encoded.']],
];

$fs = Craft::$app->getFields(); $elements = Craft::$app->getElements();
$volume = Craft::$app->getVolumes()->getVolumeByHandle('archiveMedia');
$folder = Craft::$app->getAssets()->findFolder(['volumeId' => $volume->id, 'path' => 'outside/']);
$licOpts = array_map(fn($o) => $o['value'], $fs->getFieldByHandle('license')->options);
$plan = [];
foreach ($PHOTOS as $p) {
    $rec = Entry::find()->id($p['record'])->status(null)->one();
    if (!$rec || $rec->title !== $p['recordTitle']) { echo "REFUSING: #{$p['record']} is not {$p['recordTitle']}" . PHP_EOL; return; }
    if (!is_file("$root/{$p['file']}") || sha1_file("$root/{$p['file']}") !== $p['sha1']) { echo "REFUSING: {$p['file']} is missing or not the file received" . PHP_EOL; return; }
    foreach ($p['fields'] as $h => $v) {
        $f = $fs->getFieldByHandle($h);
        if (!$f || !$volume->getFieldLayout()->getFieldByHandle($h)) { echo "REFUSING: $h is not on the asset layout" . PHP_EOL; return; }
        if ($f instanceof \craft\fields\PlainText && $f->charLimit && mb_strlen($v) > $f->charLimit) { echo "REFUSING: $h is " . mb_strlen($v) . " characters, limit {$f->charLimit}" . PHP_EOL; return; }
    }
    $licOk = in_array($p['fields']['license'], $licOpts, true);
    $existing = Asset::find()->volumeId($volume->id)->filename($p['filename'])->one();
    $cur = $rec->featuredImage->one();
    if ($cur && (!$existing || $cur->id !== $existing->id)) { echo "#{$p['record']} already features #{$cur->id} {$cur->filename}; kept" . PHP_EOL; continue; }
    echo "#{$p['record']} {$p['recordTitle']}: " . ($existing ? 'asset held as #' . $existing->id : 'import outside/' . $p['filename']) . ($cur ? ', already featured' : ', featured') . PHP_EOL;
    foreach ($p['fields'] as $h => $v) { echo '   ' . str_pad($h, 15) . $v . PHP_EOL; }
    if (!$licOk) { echo '   NOTE: licence option ' . $p['fields']['license'] . ' does not exist yet; apply add_license_cc_by_sa_2.php first' . PHP_EOL; }
    $plan[] = [$p, $existing, $licOk];
}
if (!$APPLY) { echo str_repeat('=', 78) . PHP_EOL . 'nothing was written. Set $APPLY = true to apply.' . PHP_EOL; return; }
$short = [];
foreach ($plan as [$p, $asset, $licOk]) {
    if (!$licOk) { $short[] = $p['recordTitle'] . ': licence option missing'; continue; }
    if (!$asset) {
        $tmp = sys_get_temp_dir() . '/' . $p['filename'];
        copy("$root/{$p['file']}", $tmp);
        $asset = new Asset(); $asset->tempFilePath = $tmp; $asset->setFilename($p['filename']); $asset->newFolderId = $folder->id; $asset->setVolumeId($volume->id);
        $asset->setScenario(Asset::SCENARIO_CREATE); $asset->avoidFilenameConflicts = false;
        if (!$elements->saveElement($asset)) { $short[] = $p['recordTitle'] . ': ' . json_encode($asset->getFirstErrors()); continue; }
    }
    $asset = Asset::find()->id($asset->id)->one();
    $asset->title = $p['title']; $asset->alt = $p['alt'];
    $vals = $p['fields']; $vals['sourceUrl'] = ['type' => 'url', 'value' => $vals['sourceUrl']];
    $asset->setFieldValues($vals);
    if (!$elements->saveElement($asset)) { $short[] = $p['recordTitle'] . ' fields: ' . json_encode($asset->getFirstErrors()); continue; }
    $rec = Entry::find()->id($p['record'])->status(null)->one();
    if (!$rec->featuredImage->exists()) { $rec->setFieldValue('featuredImage', [$asset->id]); $elements->saveElement($rec); }
    $b = Entry::find()->id($p['record'])->status(null)->one();
    if (($b->featuredImage->one()->id ?? null) !== $asset->id) { $short[] = $p['recordTitle'] . ': not featured'; }
    if ((string)Asset::find()->id($asset->id)->one()->getFieldValue('license')->value !== $p['fields']['license']) { $short[] = $p['recordTitle'] . ': licence'; }
}
echo 'READ-BACK ' . ($short ? 'SHORT: ' . implode('; ', $short) : 'OK: both featured, with credit and licence') . PHP_EOL;
$applyLog = require $root . '/scripts/import/_apply_log.php';
$applyLog('import_city_hall_csun_photos.php', count($plan), $short ? 'SHORT: ' . implode('; ', $short) : 'verified', 'City Hall (Flickr, CC BY-SA 2.0) and CSUN (Commons, CC BY-SA 3.0)');
if ($short) { throw new \RuntimeException('import_city_hall_csun_photos: ' . implode('; ', $short)); }
