/**
 * Four records from inventory/review/schools-church-sheriff-2026-10-04.md (sources saved in
 * inventory/news/schools-church-sheriff-2026-10-04/). Nathan, 4 October 2026: "Yes to the SCV Sheriff's Station record in Valley
 * government, with the Department staying in the County's card"; Santa Clarita Christian School and Santa Clarita Baptist Church
 * "Attribute it to the school, since it is their own account"; Newhall Elementary: "Source every date properly ... Wikipedia is the
 * lead, not the citation"; "The 1876 date also makes this the oldest school in the valley, which should be stated once we have it
 * sourced."
 *  - Santa Clarita Valley Sheriff's Station: new, government, level valley, under the Sheriff's Department (#29282).
 *  - Santa Clarita Baptist Church: new, church; formed 1981 by merger; its own history the source, attributed.
 *  - Santa Clarita Christian School (#21783, an empty record): text, address, founded 1982 (attributed), under the church.
 *  - Newhall Elementary School (#15958): its history. Not 1876 (no source; the district dates from 10 May 1877); not "the oldest
 *    school in the valley" (Sulphur Springs, 1872); the Walnut Street school opened in September 1925 by the contemporary Signal,
 *    not 1928; the third school's date, 1911 or 1914, and the 1914 fire are left unresolved, as the sources disagree.
 *  - Newhall School District (#21590): founded 10 May 1877.
 * Idempotent. Dry run by default. Set $APPLY = true to write.
 * Run: ddev craft exec "eval(file_get_contents('scripts/import/schools_church_sheriff_2026_10_04.php'))"
 */
use craft\elements\Entry;
$APPLY = false;
echo ($APPLY ? 'APPLYING' : 'DRY RUN') . PHP_EOL;
$el = Craft::$app->getElements(); $svc = Craft::$app->getEntries();
$fn = fn(array $x) => array_map(fn($i, $t) => ['number' => (string)($i + 1), 'note' => $t, 'source' => 'editorial-2026'], array_keys($x), $x);
$CS = 'as carried on SCVHistory.com';
/* the Sheriff's Station */
$ST_BODY = "The Santa Clarita Valley Sheriff's Station is the Los Angeles County Sheriff's Department station that polices the valley: the City of Santa Clarita and the unincorporated communities around it, from Castaic and Val Verde to Stevenson Ranch and Sand Canyon.[1] The City has no police department of its own. It contracts with the County for police services, and the station's captain serves as its chief of police; the captain since August 2025 is Brandon Barclay.[2][3]\n\nThe station began as Substation No. 6, opened on 26 August 1926 in a former house at the northeast corner of Spruce Street and Sixth Street in Newhall, today's Main and Sixth.[4][5] In 1972 it moved to the County Civic Center, at 23740 Magic Mountain Parkway in Valencia.[5][6] The present station, at 26201 Golden Valley Road, was built by the City and the County together: ground was broken on 25 July 2018, the ribbon was cut on 18 October 2021, and the station went into service in November 2021.[6][7][8]";
$ST_NOTES = ['Los Angeles County Sheriff\'s Department, "Santa Clarita Valley Station," https://lasd.org/santa-clarita-valley/, read 4 October 2026: 26201 Golden Valley Road; the areas it serves, among them the City of Santa Clarita, Castaic, Val Verde, Stevenson Ranch and Sand Canyon.',
    'City of Santa Clarita, Candidate Handbook 2024, page 4, https://santaclarita.gov/city-clerk/wp-content/uploads/sites/8/2024/07/Candidate-Handbook-2024_Final.pdf: "Contract City - Fire and Public Safety."',
    'City of Santa Clarita release, as carried by SCVNews, August 14, 2025, https://scvnews.com/city-of-santa-clarita-announces-brandon-barclay-as-new-chief-of-police/: Brandon Barclay chosen as captain of the Santa Clarita Valley Sheriff\'s Station, the City\'s chief of police, succeeding Justin Diez.',
    'Leon Worden, "Sheriff celebrating 70 years in Newhall," The Signal, November 8, 1996, ' . $CS . ' (archive article #12292), quoting the Newhall Signal of 1926: Substation No. 6 opened on August 26, 1926, in the former Albert Swall residence at Spruce and Sixth.',
    'Caption to photograph LW3347, Personnel of Substation No. 6, 1959, ' . $CS . ', /scvhistory/lw3347.htm (archive photograph #5187): the substation at the northeast corner of Spruce and Sixth (today\'s Main and Sixth), replaced in May 1972 by the station in the County Civic Center.',
    'City of Santa Clarita release, July 25, 2018, ' . $CS . ', /scvhistory/sc1806.htm: groundbreaking for the new station on Golden Valley Road, built by the City and the County; the old station at 23740 Magic Mountain Parkway, opened in 1972.',
    'Los Angeles County Sheriff\'s Department release, as carried by SCVNews, October 18, 2021, https://scvnews.com/lasd-local-officials-unveil-new-scv-sheriffs-station/: the new station at 26201 Golden Valley Road unveiled with a ribbon cutting, to replace 23740 Magic Mountain Parkway.',
    'Los Angeles County Sheriff\'s Department station page, as captured by the Wayback Machine on November 8, 2021 (address 23740 Magic Mountain Parkway), https://web.archive.org/web/20211108231530/https://lasd.org/santa-clarita-valley/, and on November 19, 2021 (26201 Golden Valley Road), https://web.archive.org/web/20211119193812/https://lasd.org/santa-clarita-valley/. The day the station moved is not yet established.'];
/* the church */
$CH_BODY = "Santa Clarita Baptist Church, at 27249 Luther Drive in Canyon Country, was formed in 1981 when two Baptist congregations a mile apart merged: the First Baptist Church of Saugus and Temple Baptist Church of Canyon Country.[1][2] By the church's own history, the merged congregation first met under its new name on 31 May 1981, on the First Baptist site, where building had begun in 1968. First Baptist had begun on 19 November 1962, meeting in Amos Clemmons's garage; Temple Baptist first met on 11 January 1976.[1] In 1982 the church founded Santa Clarita Christian School, on the same campus.[3]";
$CH_NOTES = ['Santa Clarita Baptist Church, "Our History," as captured by the Wayback Machine on October 6, 2016, https://web.archive.org/web/20161006144241/http://www.scbc.cc:80/our-history/. The church\'s own account: the dates rest on it alone.',
    'Santa Clarita Baptist Church, home page, https://www.scbc.org/, read 4 October 2026: 27249 Luther Drive, Santa Clarita.',
    'Santa Clarita Christian School, "Mission and History," https://sccs.org/about/mission-and-history/, read 4 October 2026: "founded in 1982 as a ministry of Santa Clarita Baptist Church."'];
/* the school */
$SC_BODY = "Santa Clarita Christian School is a private Christian school, kindergarten through twelfth grade, at 27249 Luther Drive in Canyon Country, on the campus of Santa Clarita Baptist Church. The federal survey of private schools counted 552 students there in 2023-24.[1] The school's own history says it was founded in 1982 as a ministry of the church and opened with 110 students and 12 faculty, and that it has since graduated more than 1,000 students; the church dates the founding to September 1982.[2][3]";
$SC_NOTES = ['National Center for Education Statistics, Private School Universe Survey, 2023-24, Santa Clarita Christian School, NCES ID 02113668, https://nces.ed.gov/surveys/pss/privateschoolsearch/: 27249 Luther Dr, Santa Clarita, CA 91351; kindergarten to grade 12; 552 students; Baptist.',
    'Santa Clarita Christian School, "Mission and History," https://sccs.org/about/mission-and-history/, read 4 October 2026. The school\'s own account: what rests on it alone is attributed.',
    'Santa Clarita Baptist Church, "SCCS," https://www.scbc.org/sccs, read 4 October 2026: "Founded in September 1982."'];
/* Newhall Elementary */
$NE_BODY = "Newhall Elementary School is the Newhall School District's first and oldest school. The district was formed on 10 May 1877, on the petition of J.F. Powell and 47 others, and where its first classes met is not known.[1][2] It is not the valley's oldest school: the Sulphur Springs district dates from September 1872.[3]\n\nIn 1878, after the new town of Newhall had moved two miles south to its present site, classes were held in a building on the Sanford Lyon ranch, a corner of Addi Lyon's bunkhouse, which Leon Worden places roughly where the Valencia Marketplace stands today.[4][2][5] The first schoolhouse, believed to date from 1879 and paid for largely by Judge Powell, at $3,500, stood at the northeast corner of Ninth and Walnut streets: two storeys, with a hall upstairs where Sunday school met.[4][2][6] It burned in May 1890; the Los Angeles Herald of 4 June reported that the school had \"burned down at that place a few days ago.\"[7] It was rebuilt on the same site that year, again of two storeys, with help from H.C. Needham.[4][2][8]\n\nThe third school stood near the northwest corner of Newhall Avenue and what is now Lyons Avenue. The sources disagree on when and why: the Newhall History Project of 1940 dates it to 1911 and says the old site had grown too small, while Jerry Reynolds dates it to 1914, after a fire that no contemporary report has been found to confirm.[4][9][2] Pupils went on to San Fernando High School after it opened in 1896, and in 1932 the district acquired a 31-seat bus.[2][10]\n\nThe fourth school, on Walnut Street at Eleventh, opened on 14 September 1925. That August the Newhall Signal had invited parents to inspect \"the new school house\", and in November the old Lyons Avenue property was sold to A.B. Perkins. Wings were added in 1930.[11][12][13] Some later accounts, among them Reynolds's, give 1928.[9] Fire destroyed all but the north wing early on 14 February 1939, and the present building was first occupied on 10 May 1940, on the same site, now 24607 North Walnut Street.[14][4][15]";
$NE_NOTES = ['Mary F. Brunner and others, Newhall History Project, June 1940, "Newhall School District," ' . $CS . ', /scvhistory/brunner1940nsd.htm: the district formed May 10, 1877, on the petition of J.F. Powell and 47 others.',
    'Leon Worden, "History of Newhall School," Old Town Newhall Gazette, September 1997, revised 2020, ' . $CS . ', /scvhistory/newhallschool.htm.',
    'Jerry Reynolds, History of the Santa Clarita Valley, chapter 33, ' . $CS . ', /scvhistory/signal/reynolds/part33.html: the Sulphur Springs School District formed in September 1872, "second-oldest school district in Los Angeles County."',
    'Mary F. Brunner and others, Newhall History Project, June 1940, "History of Newhall Elementary School," ' . $CS . ', /scvhistory/brunner1940newhallschool.htm.',
    'Jerry Reynolds, History of the Santa Clarita Valley, chapter 49, ' . $CS . ', /scvhistory/signal/reynolds/part49.html (archive article #2123): children taught in a bunk house on Lyon land in 1878.',
    'Jerry Reynolds, History of the Santa Clarita Valley, chapter 36, ' . $CS . ', /scvhistory/signal/reynolds/part36.html (archive article #2097): Judge Powell\'s $3,500 toward the first official Newhall School, 1879.',
    'Los Angeles Herald, June 4, 1890, ' . $CS . ', /scvhistory/lp_laherald060490school.htm.',
    'Jerry Reynolds, History of the Santa Clarita Valley, chapter 47, ' . $CS . ', /scvhistory/signal/reynolds/part47.html (archive article #2119): the school at Ninth and Walnut burned in 1890 and was rebuilt with Needham\'s help.',
    'Jerry Reynolds, History of the Santa Clarita Valley, chapter 71, ' . $CS . ', /scvhistory/signal/reynolds/part71.html: fires of 1890 and 1914; the third school near the northwest corner of Newhall Avenue and Lyons; a move to Eleventh in 1928.',
    'Mary F. Brunner and others, Newhall History Project, June 1940, "Newhall Elementary School Bus System," ' . $CS . ', /scvhistory/brunner1940newhallschoolbus.htm: a 31-seat Chevrolet bus acquired in 1932.',
    'The Newhall Signal, August 20 and September 3, 1925, ' . $CS . ', /scvhistory/tlp_signal082025b.htm: "the new school house" to be inspected; school opens September 14, 1925, in the new building.',
    'The Newhall Signal, November 12, 1925, and following issues, ' . $CS . ', /scvhistory/tlp_signal082025.htm: the old school property sold to A.B. Perkins for $4,910 and the building split into three.',
    'The Newhall Signal, February 17, 1939, ' . $CS . ', /scvhistory/tlp_signal021739pg3.htm: the building "erected in 1925", its wings added in 1930.',
    'Los Angeles Times, February 15, 1939, and the Associated Press, ' . $CS . ', /scvhistory/tlp_lat021539pg2.htm: the Newhall grammar school destroyed by fire early on February 14, 1939.',
    'Newhall Elementary School, "About Us," https://nh.newhallschooldistrict.com/about-us, read 4 October 2026: 24607 North Walnut Street, Newhall.'];
$LASD = Entry::find()->id(29282)->status(null)->one(); $SCCS = Entry::find()->id(21783)->status(null)->one(); $NE = Entry::find()->id(15958)->status(null)->one(); $NSD = Entry::find()->id(21590)->status(null)->one();
$bad = []; foreach ([[$LASD, "Los Angeles County Sheriff's Department"], [$SCCS, 'Santa Clarita Christian School'], [$NE, 'Newhall Elementary School'], [$NSD, 'Newhall School District']] as [$e, $t]) { if ($e?->title !== $t) { $bad[] = "not $t"; } }
if (trim(strip_tags((string)$NE?->body)) !== '' && !str_contains((string)$NE->body, '10 May 1877')) { $bad[] = 'Newhall Elementary already has text'; }
if (trim(strip_tags((string)$SCCS?->body)) !== '' && !str_contains((string)$SCCS->body, 'Luther Drive')) { $bad[] = 'SCCS already has text'; }
echo 'REFUSED: ' . ($bad ? implode(' | ', $bad) : 'none') . PHP_EOL;
if (!$APPLY || $bad) { return; }
$n = 0; $os = $svc->getSectionByHandle('organizations'); $PROV = 'schools_church_sheriff_2026_10_04.php, 4 October 2026';
$make = function ($title, $v) use ($os, $el, &$n) { $e = Entry::find()->section('organizations')->status(null)->title($title)->one();
    if (!$e) { $e = new Entry(); $e->sectionId = $os->id; $e->setTypeId($os->getEntryTypes()[0]->id); $e->title = $title; }
    if (!str_contains((string)$e->body, mb_substr(strip_tags($v['body']), 0, 40))) { $h = array_map(fn($f) => $f->handle, $e->getFieldLayout()->getCustomFields()); $e->setFieldValues(array_intersect_key($v, array_flip($h))); if (!$el->saveElement($e)) { throw new \RuntimeException("$title " . json_encode($e->getFirstErrors())); } $n++; }
    return $e; };
$make("Santa Clarita Valley Sheriff's Station", ['orgType' => 'government', 'orgLevel' => 'valley', 'hasParentOrg' => true, 'parentOrganization' => [29282], 'body' => $ST_BODY, 'footnotes' => $fn($ST_NOTES), 'dateFounded' => 'August 26, 1926', 'dateFoundedEdtf' => '1926-08-26', 'foundedEvidence' => 'contemporary', 'orgAddress' => '26201 Golden Valley Road, Santa Clarita, CA 91350', 'recordProvenance' => $PROV]);
$church = $make('Santa Clarita Baptist Church', ['orgType' => 'church', 'body' => $CH_BODY, 'footnotes' => $fn($CH_NOTES), 'dateFounded' => 'May 31, 1981', 'dateFoundedEdtf' => '1981-05-31', 'foundedEvidence' => 'retrospective', 'orgAddress' => '27249 Luther Drive, Santa Clarita, CA 91351', 'recordProvenance' => $PROV]);
$make('Santa Clarita Christian School', ['body' => $SC_BODY, 'footnotes' => $fn($SC_NOTES), 'hasParentOrg' => true, 'parentOrganization' => [$church->id], 'dateFounded' => '1982', 'dateFoundedEdtf' => '1982', 'foundedEvidence' => 'retrospective', 'orgAddress' => '27249 Luther Drive, Santa Clarita, CA 91351', 'gradeSpan' => 'K to 12', 'recordProvenance' => trim((string)$SCCS->recordProvenance . '; ' . $PROV)]);
$make('Newhall Elementary School', ['body' => $NE_BODY, 'footnotes' => $fn($NE_NOTES), 'dateFounded' => '1877', 'dateFoundedEdtf' => '1877', 'foundedEvidence' => 'retrospective', 'orgAddress' => '24607 North Walnut Street, Newhall, CA 91321', 'recordProvenance' => trim((string)$NE->recordProvenance . '; ' . $PROV)]);
if ((string)$NSD->dateFoundedEdtf !== '1877-05-10') { $NSD->setFieldValues(['dateFounded' => 'May 10, 1877', 'dateFoundedEdtf' => '1877-05-10', 'foundedEvidence' => 'retrospective']); if (!$el->saveElement($NSD)) { throw new \RuntimeException('NSD'); } $n++; }
$applyLog = require \Craft::getAlias('@root') . '/scripts/import/_apply_log.php'; $applyLog('schools_church_sheriff_2026_10_04.php', $n, 'verified', 'SCV Sheriff\'s Station; Santa Clarita Baptist Church; Santa Clarita Christian School; Newhall Elementary\'s history; Newhall School District founded 1877');
echo "done: $n writes" . PHP_EOL;
